### ISSUE TITLE
Implement pop-up screens appearing on loss and win.

### ISSUE THREAD

**Issue by default-jamc** [UQdeco2800/2021-studio-3#10]
# Description
**Task Name:** Implement pop-up screens appearing on loss and win.
**Feature:** Win / Loss Conditions & Visualisation #8 

The 'win' and 'loss' screens will need to appear when the player, 
- clears the level: reaches the right-most of the screen and,
- loses the level: their health reaches 0

Both windows will be pop-ups with the Main Game Screen displayed behind them. The pop-up menus will make use of the `Entity` class, which will have `UIComponent`s that extend the `UIComponent` class, to allow for functioning buttons.

# Dependencies
- [x] Screens need to be designed (before final implementation into game)

# Milestones
- [x] Update existing `Win / Loss Condition & Visualisation` Wiki page (Aug. 21)
- [x] Create class for `DeathPopupScreen` (Aug. 22)
- [x] Create class for `WinPopupScreen` (Aug. 22)
- [x] Create `Event` to trigger the `DeathPopUp` (Aug. 23)
- [x] Create `Event` to trigger the `WinPopUp` (Aug. 23)
- [x] Update Wiki documentation (Aug. 25)

**Completion Deadline:** Aug. 25

# Documentation
- [Wiki page](https://github.com/UQdeco2800/2021-studio-3/wiki/Loss-&-Win-In-Game-Menus)

# Member
- Jazmin (@default-jamc)
