### ISSUE TITLE
Fix bugs for movement animations

### ISSUE THREAD

**Issue by SirAardvark** [UQdeco2800/2021-studio-3#100]
## Description
Feature: Refine character movement animations #91

The player state component and the player animation controller sometimes display the incorrect animation. 

### Known Bugs
Major Bugs:
- Player is holding A and D then stops holding one, the stationary animation is played when they are moving
- Player is moving then sprinting, sprint animation does not play

Minor Bugs:
- Player jumps and animation loops at a slow speed (Should only happen once on pressing spacebar)
- Player animations still change once end is reached
- Death animation is incorrect orientation (Vertical instead of horizontal)

## Milestones
- [ ] Fix existing bugs where player state is not set properly and wrong animation is played
- [ ] Fix Death animation being in the wrong orientation
- [ ] Player can input animations after end is reached

## Member
Justin (@SirAardvark )

**Comment by SirAardvark** [comment]
20/09 - Fixed issue where incorrect animation is being played and sprint now triggers once you start sprinting (0ef01c4afbcf4680147c1405938a51972fa5a688). Re-worked part of the PlayerStateComponent to get the correct player state/direction.

**Comment by Dollar0712** [comment]
Already disabled the animation when the game state is not in 'RUNNING'
