### ISSUE TITLE
Death Wall Monster Implementation

### ISSUE THREAD

**Issue by BasJW** [UQdeco2800/2021-studio-3#101]
# Description

A large monster will traverse left to right chasing the player. A key characteristic of the monster is its ability to phase through objects. If the player falls behind and makes contact with the monster, the player will die immediately.

Implementation of the monster will be done in `ObstacleFactory`, with plans to also use `PlayerStateComponent` to manage the health loss the player will colliding with the monster.

# Milestones

 - [x] Create death wall wiki page (Sept. 21)
- [x] Add an object which continuously moves right (Sept. 21)
- [x] Allow the object to ignore obstacles (Sept. 22)
- [x] Kill player when in contact with the monster (Sept. 23)
- [x] Document code with sufficient JavaDoc (Sept. 24)
- [x] Finalise wiki page (Sept. 25)

**Completion deadline: 25th september**

# Documentation

 - [Wiki page](https://github.com/UQdeco2800/2021-studio-3/wiki/Death-Wall-Monster)

# Member(s)
 - Kevin (Dollar0712)
 - Sebastian (BasJW)
