### ISSUE TITLE
Design Player Movement Effects & Sound Effects

### ISSUE THREAD

**Issue by WendyW16** [UQdeco2800/2021-studio-3#103]
# **Description**
**Task Name:** Design player movement effect & sound effects
**Feature:** Additional Player Movement #93  & Sound Effects Design #92

Design extra movements when the player is doing extra moves. 
Design interactive sound 

### **Movement Effect**
double jump -- while mid-air, the player can jump again
instant drop -- while mid-air, the player can drop to the ground faster

### **Sound Effect**
Interactive Sounds -- Clicking menu buttons

## **Milestones**
- [x] Research (Sept. 22)
- [x] Design some sketches（Sept. 25)
- [x] Design double jump & instant drop effects(Sept. 27)
- [x] Design interactive sound(Sept. 28)
- [x] Redesign（Oct. 2）
- [x] Create wiki document(Oct. 4)

*Completion Deadline:* Oct. 5

## **Documentation**
- [Wiki page *To be created*](https://github.com/UQdeco2800/2021-studio-3/wiki)

## **Members**
- Wendy (@WendyW16)

**Comment by WendyW16** [comment]
![画板 5 副本](https://user-images.githubusercontent.com/88033083/135750877-fc0df294-bcbf-4a6d-ab83-02f2267b3d1f.png)
![画板 5](https://user-images.githubusercontent.com/88033083/135750888-93d3f51a-4593-4d67-a0e7-9ec5567b6db5.png)

**Comment by WendyW16** [comment]
![画板 5](https://user-images.githubusercontent.com/88033083/135750888-93d3f51a-4593-4d67-a0e7-9ec5567b6db5.png)
