### ISSUE TITLE
Refining front view damage aesthetics and sizing

### ISSUE THREAD

**Issue by paulchoi610** [UQdeco2800/2021-studio-3#105]
**Feature ticket:** Refine character movement animations #91 

The front idle view of the character for the 50-89 damage state is visually inconsistent with the side view and thus should be changed. The size of the idle front view is also disproportionately large compared to the side view and should be narrowed as a result.

## Milestones
- [] Edit the front idle view of the character for the 50-89 damage state
- [] Change dimensions of side view
- [] Convert to GDX sprite sheet and atlas

## Member
Paul (@paulchoi610)
