### ISSUE TITLE
Design the character movement response

### ISSUE THREAD

**Issue by n1ko4fun** [UQdeco2800/2021-studio-3#107]
### Description
**Task Name:** Design the character movement response.
**Features:** Additional Player Movement #93

As this sprint, teams three decided to implement additional player movement which included "double jump", "wall Jump", "Instant Jump" and "Roll" to enrichment game content. For my part, I have to design a few movement animation.

### Movement Effect
Wall Jump: while touching a wall, the player can use is to jump in the other direction.
Roll: the player can roll to move forwards faster.

### Milestones

- [x] Research of movement arrangement(22/09)
- [x] Create a few draft for implement(22/09)
- [x] Design the Wall Jump & Roll animation(24/09)
- [x] User test for those development(26/09)
- [x] Modification based on feedback(26/09)

Completion Deadline: 05/10

### Members

- Haonan Li(@n1ko4fun )

**Comment by n1ko4fun** [comment]
![画板 1rollWiki](https://user-images.githubusercontent.com/88018782/135944895-b63b12b9-5218-411d-8ca2-6fba0c12aeed.png)
![画板 1rollRE](https://user-images.githubusercontent.com/88018782/135944915-0799d414-9874-44a2-9a03-c1af6d557f51.png)
![画板 1wallJumpWiki](https://user-images.githubusercontent.com/88018782/135944919-2183baba-44a1-40a5-84f3-d7edc8e2a1ca.png)
![画板 1wallJumpFinalWiki](https://user-images.githubusercontent.com/88018782/135944924-fa786ac1-f0dc-46c3-a984-2baa68ec5c97.png)

**Comment by n1ko4fun** [comment]
Also in sprint3, I designed the loading screen. hope it will be used someday
![loadingF1](https://user-images.githubusercontent.com/88018782/135947027-77f5f2b7-8a1e-46c4-9b2d-a22574b88f01.png)
![loadingF2](https://user-images.githubusercontent.com/88018782/135947031-fc316372-d6c7-49ce-8ab9-2a1ba91ca8b5.png)
![loadingF3](https://user-images.githubusercontent.com/88018782/135947033-0f169901-a4dc-4ed5-bb3c-651f575cf9b8.png)
![loadingF4](https://user-images.githubusercontent.com/88018782/135947035-5f2db737-a0c5-42f3-875c-64b2b420b191.png)
![loadingF5](https://user-images.githubusercontent.com/88018782/135947037-f54cd847-161b-443e-8bbf-131ef55deee5.png)
![loadingF6](https://user-images.githubusercontent.com/88018782/135947038-36b76fa4-326c-4186-aee6-9feaae456667.png)
![loadingF7](https://user-images.githubusercontent.com/88018782/135947042-5cc6a120-d2e5-489c-a818-d5f04a0fcb32.png)
.
