### ISSUE TITLE
Implement new floor System (1)

### ISSUE THREAD

**Issue by K0zzas17** [UQdeco2800/2021-studio-3#108]
# Description
**Task Name**: Implement new floor system
**Feature**: #80 Implementing a new level design

Implementing a new floor system will allow for a more varied and dynamic floor design. This implementation will be crucial for the design of future levels.

Implementing a new floor system will make changes to the `ForestGameArea` and `TerrainFactory` classes. Possibility for a new class implementation.

# Milestones
- [x] Update wiki documentation for new main game floor (25/09)
- [x] Explore the possibility of implementing buffReader to read a file with the level parameters on it (27/09)
- [x] Implement buffReader (if applicable)
- [x] Create new varying floor conditions within `ForestGameArea.java` (29/09)
- [x] Implement new conditions for the first level (30/09)
- [x] Update Documentation (30/09)

# Documentation
- [Main Game Floor](https://github.com/UQdeco2800/2021-studio-3/wiki/Main-game-floor-Implementation)
# Members
- Onai @K0zzas17 
- Liam @Gir3245
