### ISSUE TITLE
Design Death Wall Enemies

### ISSUE THREAD

**Issue by yeegoh** [UQdeco2800/2021-studio-3#109]
# Description
A death wall will continuously move left to right (#110), forcing the player to either keep moving right or take large amounts of damage whilst coming into contact with the death wall. The death wall will be designed in the form of a Viking-inspired monster to align with the game story. 

## Milestones
**Goal 1 - Sketch monster design prototypes**
- [x] Level 1 monster design prototypes
- [x] Level 2 monster design prototypes

**Goal 2 - Design monster graphics**
- [x] Level 1 monster graphics
- [x] Level 2 monster graphics

**Goal 3 - Create monster animations** 
- [x] Create frames for level 1 monster animations (Ticket #141) (@paulchoi610)
- [x] Convert frames into GDX spritesheets and atlases (Ticket #141) (@paulchoi610)
~~- [ ] Create frames for level 2 monster animations~~
~~- [ ] Convert frames into GDX spritesheets and atlases~~

---
- [x] Update wiki
## Documentation:
**Enemy Monster Animations:** https://github.com/UQdeco2800/2021-studio-3/wiki/Enemy-Monster-Animations

## Members
Paul (@paulchoi610)

**Comment by paulchoi610** [comment]
@yeegoh When you say designing the graphics are you referring to creating the actual design on illustrator or did you mean animations. I've assumed you meant making the actual design on illustrator and added another part for animations.

Furthermore, I think we may need to make this a feature ticket, the amount of intermediate tasks and time required to complete them makes it unsuited to being a task ticket. The death wall implementation feature (code functionality) #110 can then just be dependent on this one to connect them. What do you think?

**Comment by yeegoh** [comment]
Yeah I agree with all of the above, the information added before was more of a placeholder as I did not know what your team's plan was.

**Comment by yeegoh** [comment]
Sorry for the delay, I was doing sketches and waiting for user feedback on them. Here are some sketches for a potential serpent/leviathan/dragon monster and also a fire rock gollum things. The people I asked said they liked 2, 4, 7 and 8 for various reasons. I'm not sure where to put the feedback.   
<img src="https://user-images.githubusercontent.com/70673799/135196354-40233731-98d0-40d5-b4a7-f3ffe32f56c1.jpg" width="500">

Here are the graphics for designs 2, 4, 7 and 8:
<img src="https://user-images.githubusercontent.com/70673799/135196804-e79846ae-b221-44d3-b3a5-67214919f3a9.PNG" width="300">
<img src="https://user-images.githubusercontent.com/70673799/135196852-46cc4d07-5c98-42bf-88ca-84ebffc0a732.PNG" width="300">

Here is what a monster might potentially look like in the game:
<img src="https://user-images.githubusercontent.com/70673799/135196012-663de542-cf7f-4dff-9ef0-fb2683e89d40.PNG" width="600">

I am in the process of gathering user feedback for possible death wall enemy designs.

**Comment by paulchoi610** [comment]
@yeegoh Looks great, i'm happy with whatever results from the design process. I think you should detail your design process and feedback in a wiki page to show and document your work. I'll create a wiki page for the animations so we can lump them together under the same heading.

**Comment by paulchoi610** [comment]
![image](https://user-images.githubusercontent.com/88036593/135417766-65d34381-fe0f-4688-bdfe-25dd7fe92f72.png)

Feel free to add your wiki page under this heading in the contents.
