### ISSUE TITLE
Implement Player Sprinting Functionality

### ISSUE THREAD

**Issue by BasJW** [UQdeco2800/2021-studio-3#11]
# Description
**Task:** Player Sprinting Functionality
**Feature:** Additional Player Movement & Animations #5 

This task will allow the player to have a brief boost of speed. When the player holds down space, the default walk speed will temporarily be increased. At the same time, the "Sprint status" number will decrease. Once this reaches 0, the player will no longer be able to sprint anymore, and will need to wait for it to recharge.

At this point, sprint functionality will be implemented within the `KeyboardPlayerInputComponent` class. Whilst the sprint key is held down, the sprint gauge will deplete at a certain rate, using the libgdx `Timer` class. The sprint gauge will be shown on the UI through the `PlayerStatsDisplay` class. Lastly, a new `Listener` will be implemented to listen to when the user uses the sprint functionality.

# Dependencies

- [ ] Sprint animation frames

# Milestones

- [x] Create wiki page for sprinting - Aug 21
- [x] Implement basic sprint functionality - Aug 21
- [x] Limit sprint functionality to when space bar is held down - Aug 22
- [x] Limit sprint function to only be used for a certain amount of time. - Aug 22
- [x] Implement `SprintComponent` Class - Aug 22
- [x] Update wiki documentation - Aug 23

**Completion Deadline:** Aug 23

# Documentation
[Relevant wiki page](https://github.com/UQdeco2800/2021-studio-3/wiki/Player-Sprinting-Functionality)

# Member
Sebastian (BasJW)
