### ISSUE TITLE
Death Wall Monster

### ISSUE THREAD

**Issue by BasJW** [UQdeco2800/2021-studio-3#110]
# Description

A large monster will traverse left to right chasing the player. A key characteristic of the monster is its ability to phase through objects. If the player falls behind and makes contact with the monster, the player will die immediately.

Implementation of the monster will be done in `ObstacleFactory`, with plans to also use `PlayerStateComponent` to manage the health loss the player will colliding with the monster.

**Changes:**
Originally, a moving wall was going to be implemented, however it was agreed upon that a monster would be far more suited to the idea of the game, and fit in alot better with the story.

# Dependencies

Design Death Wall Enemies #109 

# Milestones

- [x] Implement the phasing-death-monster #101 (@BasJW, @Dollar0712)
  - [x] Create death wall wiki page (Sept. 21)
  - [x] Add an object which continuously moves right (Sept. 21)
  - [x] Allow the object to ignore obstacles (Sept. 22)
  - [x] Kill player when in contact with the monster (Sept. 23)
  - [x] Document code with sufficient JavaDoc (Sept. 24)
  - [x] Finalise wiki page (Sept. 25)

# Member(s)
 - Kevin (Dollar0712)
 - Sebastian (BasJW)
