### ISSUE TITLE
UI Overhaul

### ISSUE THREAD

**Issue by raneechu** [UQdeco2800/2021-studio-3#112]
## Description
This feature focuses on polishing aspects of the game with the aim of improving the UI. For example, at the moment, the player cannot move through the fire, but rather has to jump around it where it would make more sense for the player to move through the fire and take damage. Tasks will be made along the way as ideas come through. Currently, this feature is assigned to team 3, however anyone in the studio is allowed to assign themselves and add tasks.

## Sub Feature / Components

- Implementation of tasks
- User testing to determine effectiveness of changes

## Milestones
 - [x] Implement loading bar on main menu (@raneechu) (#115)
   - [x] Write code logic
   - [x] Complete user & Junit tesing
   - [x] Documentation
- [x] Remove collision of fire asteroid obstacle so player can pass through (@raneechu)
- [x] Fix small performance issues, bugs, and overall coherency of the UI (@default-jamc) (#123) 

*Completion Deadline:* Oct. 5

## **Documentation**
- [Loading Bar Wiki](https://github.com/UQdeco2800/2021-studio-3/wiki/Loading-Bar)
- [Visual Improvements Wiki Page](https://github.com/UQdeco2800/2021-studio-3/wiki/Visual-Improvements)

## **Members**
- Jazmin (@default-jamc)
- Niko (@n1ko4fun)
- Ranee (@raneechu)
- Su (@Su-LAN)
- Wendy (@WendyW16)

**Comment by default-jamc** [comment]
[26/09] _Changelog_: The UI, Performance and Small Bug Fixes task (#123) was added to the **Milestones**, and its pertinent [wiki page](https://github.com/UQdeco2800/2021-studio-3/wiki/Visual-Improvements) was added to the **Documentation**.
