### ISSUE TITLE
Implement player actions in relation to floor changes

### ISSUE THREAD

**Issue by K0zzas17** [UQdeco2800/2021-studio-3#113]
# Description
**Task Name**: Implement player actions in relation to floor changes
**Feature**: #80 Implementing a new level design

Implementing a new floor system has allowed for different floor conditions to be met by the player. Implementing player actions in relation to floor changes will implement new player reactions to newly developed events such as falling in a hole / pit (leading to death) or running into an end wall (per #101, for example). This implementation part of the continued scheme of enhancing gameplay, and is the last non-design component of implementing a new level terrain.

Implementing a this task will make changes to the `CombatStatsCompoenent` and `ForestGameArea` classes. Possibility for a new class implementation if required.

# Milestones
- [x] Implement DeathFloor Obstacle (new config class & update json file) - 27/09
- [x] Implement "Death" boundary (i.e. if player touches this they loose 100% of their health) - 28/09
- [x] Implement player not moving through non surface walls as defined by the surface bounds 29/09
- [x] Update necessary classes relating to player getting hit and loosing health - 28/09 
- [x] Update wiki in relation to player death by pitfall - 30/09

# Documentation
- [Main Game Floor Implementation](https://github.com/UQdeco2800/2021-studio-3/wiki/Main-game-floor-implementation-changes)
# Members
- Onai @K0zzas17 
- Liam @Gir3245
