### ISSUE TITLE
Design floor layout

### ISSUE THREAD

**Issue by K0zzas17** [UQdeco2800/2021-studio-3#114]
# Description
**Task Name**: Design Floor Layout
**Feature**: #80 Implementing a new level design, #90 Multiple Game levels

Designing the level design, incorporating the newly implemented new floor terrain (Tasks #108, #111, #113). Although implementation of #80 is complete, level design of the floor will be necessary to complete implementation.

Implementing this design will make changes to  `ForestGameArea.java` , potentially others as required.

# Milestones
- [x] Create new level layout designs - 28/9
- [x] Create associated floor level layout - 30/9
- [x] Update classes to reflect the new design - 30/9
- [x] Update Documentation - 04/10

# Documentation
- [Main game floor implementation changes](https://github.com/UQdeco2800/2021-studio-3/wiki/Main-game-floor-implementation-changes)

# Members
- Onai @K0zzas17 
- Liam @Gir3245 
- Yee @yeegoh 
- Sarah @sh4453

**Comment by K0zzas17** [comment]
This task ticket is meant to reflect the level design process as adapted by Team's 2 and 5
