### ISSUE TITLE
Death wall intro camera movement

### ISSUE THREAD

**Issue by Dollar0712** [UQdeco2800/2021-studio-3#116]
# Description
An introductory camera display is necessary at the start of the game in order to make the player aware of the need to escape from the movement of the death wall.

The aim of this task is to use the camera to show the death wall before turning the view to the player.

# Dependencies
Death Wall Monster #110
Design Death Wall Enemies #109
Death Wall Monster Implementation #101

# Milestones
- [x] Implement the phasing-death-monster (@Dollar0712)
  - [x] Create a camera that can move from start to end (Sept. 21)
  - [x] Making the camera a more appropriate showing of the death wall (Sept. 22)
  - [x] Fixing bugs(Sept. 22)
  - [x] Complete Junit testing (Sept. 23)
  - [x] Document code with sufficient JavaDoc (Sept. 24)

# Member(s)
 - Kevin (Dollar0712)
