### ISSUE TITLE
Sound effect and Background music

### ISSUE THREAD

**Issue by Su-LAN** [UQdeco2800/2021-studio-3#117]
# **Description**
**Task Name:** Sound effect and Background music
**Feature:** Sound Effects Design #92

Design buff and debuff Sound effect and Background music

## **Milestones**
- [x] Design some sound effect（Sept. 27)
- [x] Design interactive sound(Sept. 30)
- [x] Code the sound effect

*Completion Deadline:* Oct. 5

## **Documentation**
- [Sounds Effects Wiki Page](https://github.com/UQdeco2800/2021-studio-3/wiki/Sound-Effects)

## **Members**
- Su-LAN
