### ISSUE TITLE
Overhaul of Jumping System

### ISSUE THREAD

**Issue by default-jamc** [UQdeco2800/2021-studio-3#118]
# Description
**Task Name:** Overhaul of Jumping System
**Feature:** Additional Player Movement #93  

The current mechanism for jumping is very restrictive and makes adding additional player movements very difficult. The current implementation will be altered to remove the requirement of Timers in the implementation, as they introduce non-deterministic behaviour.

Implementation will make changes to the `KeyboardPlayerInputComponent` class. 

# Milestones
- [ ] Update jumping mechanism (Sept. 23)
- [ ] Ensure any dependent functionality continues to work as intended (Sept. 23)
- [ ] Write additional JUnit tests if required (Sept. 24)
- [ ] Update Wiki documentation (Sept. 25)

**Completion Deadline:** Sept. 25

# Documentation
- [Current Jumping Wiki Page](https://github.com/UQdeco2800/2021-studio-3/wiki/Player-Jumping-Functionality)

# Member
- Jazmin (@default-jamc)
