### ISSUE TITLE
Implement the buttons on the pop-up screens appearing on loss and win.

### ISSUE THREAD

**Issue by Su-LAN** [UQdeco2800/2021-studio-3#12]
# Description
**Task Name:** Implement the buttons on the pop-up screens appearing on loss and win.
**Feature:** Win / Loss Conditions & Visualisation #8 

There are two buttons on each pop-up screen
- `Restart` and `Main menu` on `DeathPopupScreen`
- `Next Level` and `Main menu` on `WinPopupScreen`
- `resume`, `Restart` and `Main menu` on `PausePopupScreen`

# Dependencies
- [x] Pop-up screens and need to be designed and coded

# Milestones
- [x] Update existing `Win / Loss Condition & Visualisation` Wiki page (Aug. 22)
- [x] Create button for `Restart` (Aug. 22)
- [x] Create button for `Main menu` (Aug. 23)
- [x] Create button for `resume` (Aug. 23)
- [x] Create button for `Next Level` (Aug. 23)
- [x] Create `Event` to `Restart` (Aug. 24)
- [x] Create `Event` to `Main menu` (Aug. 24)
- [x]  Create `Event` to `Resume` (Aug. 24)
- [x] Create `Event` to `Next Level` (Aug. 24)
- [x] Update Wiki documentation (Aug. 24)

**Completion Deadline:** Aug. 25

# Documentation
- [Wiki page](https://github.com/UQdeco2800/2021-studio-3/wiki/Loss-&-Win-In-Game-Menus)

# Member
- Jazmin (@default-jamc )
