### ISSUE TITLE
Research potential design inspirations for death wall monster

### ISSUE THREAD

**Issue by paulchoi610** [UQdeco2800/2021-studio-3#121]
# Description

As the death wall will be implemented in the form of a monster chasing the player, potential design inspirations must be considered and explored. Specifically, monsters relating to the game story theme of ragnarok and norse mythology should be researched.

# Milestones
- [ ] Research potential design ideas relating to ragnarok and norse mythology monsters
- [ ] Collate inspirations for final design direction 
- [ ] Document on wiki

# Documentation

...
Members
Paul (@paulchoi610)
