### ISSUE TITLE
UI, Performance and Small Bug Fixes

### ISSUE THREAD

**Issue by default-jamc** [UQdeco2800/2021-studio-3#123]
# Description
**Task Name:** UI, Performance and Small Bug Fixes.
**Feature:** UI Overhaul #112

Some aspects of the current UI and HUD are cluttered, unclear or inconsistent with the design style of the game. Some changes will be made to the UI to improve it's visual appearance and coherency. 

Additional changes will be made to improve the performance of the game with respect to it's loading time, and some minimal bugs will be fixed.

Implementation will predominantly make changes to the `PlayerStatsDisplay` class. 

# Milestones
- [x] Create visual improvements wiki page (Sept. 26)

**Visual Improvements**
- [x] Change colour of UI buttons (`Pause`, `Exit`) to better suit the colour scheme outlined in the [Design Guide](https://github.com/UQdeco2800/2021-studio-3/wiki/Design-Guide)
- [x] Fix the aspect ratio of the Progress Tracker so that it looks as it does on its [wiki page](https://github.com/UQdeco2800/2021-studio-3/wiki/Progress-Tracker) 
    - [x] Fix spacing of the `%` on the right-hand side of the Progress Tracker. 
- [x] ~~Remove the Box Forest in the top-left UI~~. Change `Box Forest` in the top-left UI to `Level One` and `Level Two`
- [x] (Potentially) Remove `Health` in the top-left UI, as it is made redundant by the Health Bar.
- [x] Change `Exit` buttons to say `Main Menu` where appropriate.
- [x] Remove the `Exit` button on the in-game screen, as it is made redundant by the `Main Menu` button on the `Pause` Menu.
- [x] ~~(Potentially) Remove buff information from the UI~~. Make buff information more subtle on the UI.
- [x] Fix alignment of `Main Menu` text on the Pause Menu Button.

**Performance Improvements**
- [x] Remove redundant & unused texture imports in the `ForestGameArea` class.

**Bug Fixes**
- [x] Fix `Score` going into negative values.
- [x] Fix `Health` not updating on the UI when the player picks up a Full Restore buff
--------------------------------------------------------

- [x] Update Wiki documentation (Sept. 28)

**Completion Deadline:** Sept. 28

# Documentation
- [Visual Improvements Wiki Page](https://github.com/UQdeco2800/2021-studio-3/wiki/Visual-Improvements)

# Member
- Jazmin (@default-jamc)

**Comment by default-jamc** [comment]
[26/09] _Changelog_: The sub-task _Remove `Box Forest` in the top-left UI_ was changed to: Change `Box Forest` in the top-left UI to `Level One` and `Level Two`.

**Comment by default-jamc** [comment]
[27/09] _Changelog_: The '_(Potentially) Remove buff information from the UI_' sub-task was added.

**Comment by default-jamc** [comment]
[27/09] _Changelog_: The '_Fix alignment of `Main Menu` text on the Pause Menu Button_' sub-task was added.

**Comment by default-jamc** [comment]
[27/09] _Changelog_: 

- The '_Remove the `Exit` button on the in-game screen, as it is made redundant by the `Main Menu` button on the `Pause` Menu_' sub-task was added.
- The '_(Potentially) Remove buff information from the UI_' sub-task was changed to: Make buff information more subtle on the UI.
