### ISSUE TITLE
Implement Roll Functionality

### ISSUE THREAD

**Issue by default-jamc** [UQdeco2800/2021-studio-3#125]
# Description
**Task Name:** Implement Roll Functionality.
**Feature:** Additional Player Movement #93  

Roll will allow the player to move left or right very quickly, but with a large cool-down. The player will not be able to roll mid-air.

Implementation of roll will make changes to the `KeyboardPlayerInputComponent` and `PlayerActions` classes. Another class may be created to handle the additional movement also.

# Dependencies
- The final implementation of roll will depend on the pertinent movement atlases being complete (#107)

# Milestones
- [x] Create Roll Wiki Page (Sept. 30)
- [x] Update [How To Play](https://github.com/UQdeco2800/2021-studio-3/wiki/How-To-Play) and [Player Movement](https://github.com/UQdeco2800/2021-studio-3/wiki/Player-Movement) Wiki pages to include Roll. (Sept. 30)
- [x] Implement Roll (Oct. 2)
- [x] Document code (Oct. 2)
- [x] Debugging & Improvements (Oct. 2)
- [x] Complete JUnit testing (Oct. 3)
- [x] Update Wiki documentation (Oct. 3)

**Completion Deadline:** Oct. 3

# Documentation
- [Player Rolling Wiki Page](https://github.com/UQdeco2800/2021-studio-3/wiki/Player-Rolling-Functionality)

# Member
- Jazmin (@default-jamc)

**Comment by default-jamc** [comment]
[01/10] _Changelog_: The [Player Rolling Wiki Page](https://github.com/UQdeco2800/2021-studio-3/wiki/Player-Rolling-Functionality) was added to the **Documentation**.
