### ISSUE TITLE
Implement the new game areas for level two and three

### ISSUE THREAD

**Issue by ShiyanSu** [UQdeco2800/2021-studio-3#126]
# Description
**Task Name:** Implement the new game areas for level two and three
**Feature:** Multi game-levels functionality

In order to have different game settings within each level such as different game backgrounds, different obstacles and enemies, different arrangements of obstacles and enemies and so on, we have to implement the different game areas for each level to initialise and arrange the entities and terrains.

# Dependencies
- [x] Implementation of the game screens

# Milestones
- [x] Write LevelTwoArea class for level two (Sept. 22)
- [x] Write LevelThreeArea class for level three (Sept. 24)
- [x] Integrate the area for each level into corresponding game screen (Sept. 26)
- [x] Update Wiki documentation (Sept. 30)

**Completion Deadline:** Sept. 30

# Member
- Shiyan Su (@ShiyanSu)
