### ISSUE TITLE
Boss enemies feature

### ISSUE THREAD

**Issue by emily-dl** [UQdeco2800/2021-studio-3#128]
# Description

To make the game more interactive and playable for the player character, we decide to add two new types of enemies that shoot bullets and attack the player. The first type of enemy will shoot multiple bullets in a random direction (left/ right/ adjacent/ bottom) each time and the second enemy will trace the player's location and shoot to player one bullet each time. Each bullet will cause damage to the player.

# Milestones

- [x] Design enemies characters and bullets (Sept. 30th)
- [x] Do the user testing for the design (Oct. 1st)
- [x] Finalize the design (Oct. 1st)
- [x] Create the enemy attack task to attack the player character when it gets closer to the enemies (Oct. 1st) #144 
- [x] Write the `BulletHitPlayer` class to deal the damage and destroy the bullets when they hit the player (Oct. 1st) #144 
- [x] Implement the dynamic enemy - Alien Monster (Oct. 2nd) #144 
- [x] Implement the static enemy - Alien Soldier (Oct. 2nd) #146 
- [x] Implement the dynamic enemy - Alien Boss (Oct. 2nd) #147 
- [x] Integrate the enemies into the game areas (Oct. 2nd)
- [x] Write Junit test (Oct. 2nd) #150 
- [x] Write the wiki document (Oct. 3rd)

## **Documentation**
- [Wiki page for boss enemies](https://github.com/UQdeco2800/2021-studio-3/wiki/Boss-enemies)
- [Wiki page for user testing](https://github.com/UQdeco2800/2021-studio-3/wiki/Level-2-Obstacles-and-enemy)

### Members

- Emily Zeng (@emily-dl) (Emily Zeng)
- Shiyan Su (@ShiyanSu) (Shiyan Su)
- Zhiyuan Xu (@DLAmeng)
- Thomas Mann (@44806158)
