### ISSUE TITLE
Design two player-attack enemies

### ISSUE THREAD

**Issue by emily-dl** [UQdeco2800/2021-studio-3#129]
# Description 
Task: Design two new enemies that immersively interact with the player by shooting bullets that cause health damage to the game character.
Feature: #128 

# Milestones
- [x] Design the draft version. Include two enemies and two bullets 01/10
- [x] Conduct the user-testing for design 02/10
- [x] Adjust the design based on feedbacks 03/10
- [x] Design enemy animations 04/10
- [ ] Update Wiki documentation 04/10

# Documentation
