### ISSUE TITLE
Design static obstacles

### ISSUE THREAD

**Issue by yeegoh** [UQdeco2800/2021-studio-3#13]
# Description
**Task Name:** Design static obstacles
**Feature:** Obstacle Feature #7 

Different obstacles will be implemented to provide a challenge for the player and create an engaging gameplay experience. The player will be required to avoid obstacles or they will lose a certain amount of health. 

**Static Obstacles:** Platform, various rocks

# Milestones
- [x] Create colour scheme for game design (20 Aug)
- [x] Create graphics for each obstacle (24 Aug)
- [x] Update Wiki documentation (30 Aug)

# Documentation
[Design Guide](https://github.com/UQdeco2800/2021-studio-3/wiki/Design-Guide)
[Obstacles](https://github.com/UQdeco2800/2021-studio-3/wiki/Obstacles)

# Members
- Yee Ping Goh (@yeegoh) (Yee Goh)

**Comment by yeegoh** [comment]
![platform1](https://user-images.githubusercontent.com/70673799/131246611-96cc5b32-5f19-4523-95e8-8dbde51a3391.png)
![platform2](https://user-images.githubusercontent.com/70673799/131246601-6f85acbe-8142-4647-a5af-3ce428f26f4a.png)
![platform3](https://user-images.githubusercontent.com/70673799/131246604-3beb8c8c-988d-410c-906b-a1a0fd19353b.png)
![platform4](https://user-images.githubusercontent.com/70673799/131246605-c32150fd-56ff-4a81-9c38-2ec1b6709386.png)
![platform5](https://user-images.githubusercontent.com/70673799/131246606-7e3ccd59-6264-4c99-ba95-26322f1d7cf8.png)
![rock1](https://user-images.githubusercontent.com/70673799/131246607-af2815a5-d58a-4ea7-9562-e9b57ce29fd2.png)
![rock2](https://user-images.githubusercontent.com/70673799/131246608-d552cf04-5908-45b6-9a64-9d9b21c16621.png)
![rock3](https://user-images.githubusercontent.com/70673799/131246609-bbcc1fea-6628-4514-ac4a-ebbc2e72c7c5.png)
![rock4](https://user-images.githubusercontent.com/70673799/131246610-0c9b3a99-0713-4709-b83f-0d5b16df3aec.png)
