### ISSUE TITLE
New backgrounds design

### ISSUE THREAD

**Issue by emily-dl** [UQdeco2800/2021-studio-3#130]
# Description 
Task: Design two new theme backgrounds for multi-level games. One will be the Mars-based theme and the other will be the Europa-based theme.
Feature: #90 

# Milestones
- [x] Design the draft version backgrounds 23/09
- [x] Conduct the user-testing for design 25/09
- [x] Finalize the design based on feedbacks 27/09
- [x] Update Wiki documentation game backgeound 02/10

# Documentation
