### ISSUE TITLE
Implement the new game screens for levels two and three

### ISSUE THREAD

**Issue by ShiyanSu** [UQdeco2800/2021-studio-3#131]
# Description
**Task Name:** Implement the new game screens for levels two and three
**Feature:** Multi game-levels functionality

As the buffs on the latest game area are hard to dispose when generating a new game area,  we are going to write game screens for new levels In order to dispose of all the elements for the previous level and generate a new level. 

# Dependencies
- [x] Implementation of the game areas

# Milestones
- [x] Write LevelTwoScreen class for level two (Sept. 24)
- [x] Write LevelThreeScreen class for level three (Sept. 25)
- [x] Integrate with the PlayerWinActions class and PlayerWinDisplay class to respond to the event listeners for changing level (Sept. 26)
- [x] Update Wiki documentation (Sept. 30)

**Completion Deadline:** Sept. 30

# Member
- Shiyan Su (@ShiyanSu)
