### ISSUE TITLE
Re-write the win & loss actions for PopupMenuActions class

### ISSUE THREAD

**Issue by ShiyanSu** [UQdeco2800/2021-studio-3#132]
# Description
**Task Name:** Re-write the win & loss actions for PopupMenuActions class
**Feature:** Multi game-levels functionality

Re-write the functions in PopupMenuActions class that deal with the player's win & loss situations to interact with the current multi-level functionality.

# Dependencies
- [x] Implementation of the game areas
- [x] Implementation of the game screens

# Milestones
- [x] Re-write onReply() that deals with the player loss situation (Sept. 26)
- [x] Re-write onNext() that deals with the player win situation (Sept. 26)
- [x] Update Wiki documentation (Sept. 30)

**Completion Deadline:** Sept. 30

# Member
- Shiyan Su (@ShiyanSu)

**Comment by raneechu** [comment]
Hey guys, through implementing the loading screen I noticed that the onReplayWin() function always returns the player to level 1. Wasn't sure if this was the intention or if it's supposed to be that if the player was on level2 then hitting replay should replay level 2 again? Hope this makes sense
