### ISSUE TITLE
Fix the bug of the UI components for the level two and three

### ISSUE THREAD

**Issue by ShiyanSu** [UQdeco2800/2021-studio-3#133]
# Description
**Task Name:** Fix the bug of the UI components for the level two and three
**Feature:** Multi game-levels functionality

As the PopupMenuActions only considered with the game area of the first level, the popup menus including the pause menu, player loss menu and player win menu could not work after generating the new level area. In order to make all the menus work well within each level, we have to re-write the PopupMenuActions class and especially the constructors of this class.

# Dependencies
- [x] Implementation of the game areas
- [x] Implementation of the game screens

# Milestones
- [x] Re-write the constructors of PopupMenuActions class (Sept. 28)
- [x] Update Wiki documentation (Sept. 30)

**Completion Deadline:** Sept. 30

# Member
- Shiyan Su (@ShiyanSu)
