### ISSUE TITLE
Implement the new game background for level two and level three

### ISSUE THREAD

**Issue by ShiyanSu** [UQdeco2800/2021-studio-3#134]
# Description
**Task Name:** Implement the new game background for level two and level three
**Feature:** Multi-level functionality

Implement the new game backgrounds for level two game area and level three game area to echo the storyline of the game.

# Dependencies
- [x] The backgrounds of level two and level three - should be designed

# Milestones
- [x] Add the textures of new game backgrounds (Sept. 29)
- [x] Draw the new game background in TerrainFactory class for level two and level three (Sept. 29)
- [x] Update Wiki documentation (Sept. 30)

**Completion Deadline:** Sept. 30

# Member
- Shiyan Su (@ShiyanSu)
