### ISSUE TITLE
Implement the pause game functionality

### ISSUE THREAD

**Issue by raneechu** [UQdeco2800/2021-studio-3#14]
# Description
**Task Name:** Implement the pause game functionality
**Feature:** Win / Loss Conditions & Visualisation #8 

The pause screen will appear and the game will pause in the background when the player presses 'p' on the keyboard. A UI entity will be created for the pause screen with the addition of `UIComponent`s that extend the `UIComponent` class for the buttons.

# Dependencies
- [x] Screens need to be designed (before final implementation into game)

# Milestones
- [x] Update existing `Win / Loss Condition & Visualisation` Wiki page (Aug. 22)
- [x] Create class for `PauseScreen` (Aug. 22)
- [x] Create `Event` to trigger the `Pause` (Aug. 23)
- [x] Implement functionality that pauses the game in the background (Aug 25)
- [x] Update Wiki documentation (Aug. 25)

**Completion Deadline:** Aug. 25

# Documentation
- [Wiki page](https://github.com/UQdeco2800/2021-studio-3/wiki/Loss-&-Win-In-Game-Menus)

# Member
- Ranee (@raneechu)
