### ISSUE TITLE
Implement the dynamic enemy - AlienMonster

### ISSUE THREAD

**Issue by DLAmeng** [UQdeco2800/2021-studio-3#144]
# Description
**Feature Name:** Player-attack enemies feature
**Task Name:** Implement the dynamic enemy- AlienMonster
This dynamic enemy AlienMonster will spawn alien creatures to attack the player. When the player approaches, the AlienMonster will detect the player's position and distance and then spawn one alien creature each time to the position of the player character. When the player moves away from the AlienMonster, it will stop spawning alien creatures.

# Dependencies
- [x] AlienMonster and  alien creatures - should be designed
# Milestones

- [x] Create the `AttackTask` class (Sept. 29)
- [x] Create the `AttackListener` class (Sept. 29)
- [x] Implement `createAlienMonster` function to create the AlienMonster enemy in the EnemyFactory class (Sept. 29)
- [x] Implement `createAlienMonsterWeapon` function to create the AlienMonster enemy in the EnemyFactory class (Sept. 29)
- [x] Create the `BulletHitPlayer` class (Sept. 30)
- [x] Create `spawnAlienMonster` function inside the ForestGameArea class (Sept. 30)
- [x] Adjust the position of the AlienMonster within the map and integrate into the game (Sept. 30)
- [x] Update Wiki documentation (Sept. 30)
**Completion Deadline:** Sept. 30
# Member

- Zhiyuan Xu(@DLAmeng)
