### ISSUE TITLE
 Implement the static enemy- Alien Soldier

### ISSUE THREAD

**Issue by ShiyanSu** [UQdeco2800/2021-studio-3#146]
# Description
**Feature Name:** Player-attack enemies feature
**Task Name:** Implement the static enemy- Alien Soldier
This static enemy Alien Soldier will shoot bullets to attack the player. When the player approaches, the Alien Soldier will detect the player's distance and then shoot 5 bullets in different directions each time. The direction of each bullet is stable and will not be affected by the player character's position. When the player moves away from the Alien Soldier, it will stop shooting bullets.

# Dependencies
- [x] Alien Soldier and  its bullets - should be designed

# Milestones
- [x] Create the `AlienSoldierAttackListener` class (Oct. 1st)
- [x] Implement `createAlienSoldier` function to create the Alien Soldier enemy in the EnemyFactory class (Oct. 1st)
- [x] Implement `createAlienSoldierWeapon` function to create the bullet of Alien Soldier enemy in the EnemyFactory class (Oct. 1st)
- [x] Create `spawnAlienSoldier` function inside the ForestGameArea class (Oct. 1st)
- [x] Adjust the position of the Alien Soldier within the map and integrate into the game (Oct. 1st)
- [x] Update Wiki documentation (Oct. 2nd)
**Completion Deadline:** Oct. 2nd
# Member
@ShiyanSu

**Comment by default-jamc** [comment]
Hi guys, I've found a bug with the alien soldier. If the player jumps on top of the soldier and makes it descend to the floor, the game crashes. 

I've also found times where I'm nearby to them (and they're shooting projectiles), eventually the game will crash (with the same error).

I think there's something weird happening with the way the collisions are being handled and interpreted by the engine.

I've looked into the error dump generated by Java and its happening in the `createAlienSoliderWeapon` function; specifically when the body is created (`PhysicsEngine.createBody` to `World.jniCreateBody`)

I just thought I'd let you guys know incase you hadn't encountered this error. Thanks! 🪐

**Comment by ShiyanSu** [comment]
> Hi guys, I've found a bug with the alien soldier. If the player jumps on top of the soldier and makes it descend to the floor, the game crashes.
> 
> I've also found times where I'm nearby to them (and they're shooting projectiles), eventually the game will crash (with the same error).
> 
> I think there's something weird happening with the way the collisions are being handled and interpreted by the engine.
> 
> I've looked into the error dump generated by Java and its happening in the `createAlienSoliderWeapon` function; specifically when the body is created (`PhysicsEngine.createBody` to `World.jniCreateBody`)
> 
> I just thought I'd let you guys know incase you hadn't encountered this error. Thanks! 🪐

Ok I will have a look and try to fix it soon. Thx a lot.
