### ISSUE TITLE
Implement the dynamic enemy- Alien Boss

### ISSUE THREAD

**Issue by ShiyanSu** [UQdeco2800/2021-studio-3#147]
# Description
**Feature Name:** Player-attack enemies feature
**Task Name:** Implement the dynamic enemy- Alien Boss
This dynamic enemy Alien Boss will shoot bullets to attack the player. When the player approaches, the Alien Boss will detect the player's position and distance and then shoot 3 bullets in different directions each time. The direction of each bullet will depend on the current position of the player character. When the player moves away from the Alien Boss, it will stop shooting bullets.

# Dependencies
- [x] Alien Boss and  its bullets - should be designed

# Milestones
- [x] Create the `AlienBossAttackListener` class (Oct. 1st)
- [x] Implement `createAlienBoss` function to create the Alien Soldier enemy in the EnemyFactory class (Oct. 1st)
- [x] Implement `createAlienBossWeapon` function to create the bullet of Alien Soldier enemy in the EnemyFactory class (Oct. 1st)
- [x] Create `spawnAlienBoss` function inside the ForestGameArea class (Oct. 1st)
- [x] Adjust the position of the Alien Boss within the map and integrate into the game (Oct. 1st)
- [x] Update Wiki documentation (Oct. 2nd)
**Completion Deadline:** Oct. 2nd
# Member
@ShiyanSu
