### ISSUE TITLE
Testing the multiple game-level functionality 

### ISSUE THREAD

**Issue by ShiyanSu** [UQdeco2800/2021-studio-3#148]
# Description
**Feature Name:** Multiple game-level functionality
**Task Name:** Testing the multiple game-level functionality 

Write JUnit test to test whether the multiple game-level functionality could work well:
1. All the game screens and game areas could be loaded successfully.
2. The level can be changed successfully be using the win popup menu.

# Dependencies
- [x] Implementation of multi game level should be done 

# Milestones
- [x] Write JUnit test for the screens of three levels (Oct. 3rd)
- [x] Write JUnit test for the level changing (Oct. 3rd)
- [x] Update Wiki documentation (Oct. 4th)
**Completion Deadline:** Oct. 4th
# Member
@ShiyanSu
