### ISSUE TITLE
Design the pause screen appearing on paused game

### ISSUE THREAD

**Issue by Rucens** [UQdeco2800/2021-studio-3#15]
# **Description**
**Task Name**: Design pause screen appearing on a paused game.
**Feature**: Win / Loss Conditions & Visualisation #8

The pause screens will need to appear when the player,

- Pauses the game via button

The pause screen will be a pop-up with the Main Game Screen displayed behind them. It will showcase ability to

- Resume the game
- Restart the game
- Go to Settings
- Go back to main menu
 
# **Milestones**
- [ ] Design a sketch of the pause screen(Aug. 20)
- [ ] Design pause screen based on sketch(Aug. 22)
- [ ] Update wiki documentation(Aug 24)
 
**Completion Deadline:** Aug. 24
 
 
# **Documentation**
- [Wiki link](https://github.com/UQdeco2800/2021-studio-3/wiki/Loss-&-Win-In-Game-Menus)

 
# **Member**
- Wendy (@WendyW16 ) 
- Dave (@Rucens)
- Niko (@n1ko4fun )

**Comment by n1ko4fun** [comment]
[](url)
