### ISSUE TITLE
Implementing Intro screens & updating main menu

### ISSUE THREAD

**Issue by K0zzas17** [UQdeco2800/2021-studio-3#158]
# Description
This features implements a set of intro screens in form of a slideshow to provide background for the game's story. Without background, the format and gameplay of a game can be confusing for new players. The intro scenes will help set the scene, tone and pace of the game.

As the story is not very complex, visual aspect of the scenes was decided to be the focus. Rather making the player read walls of text. 

The main menu backdrop was also changed from the default to better represent the game, which is now informally known as Meteor Man.

## Sub-Features
- User-testing to gauge reaction to visually focused intro scenes

## Milestones
- [x] Create / Update wiki related to game intro - 01/10
- [x] Update main menu background - 03/10
- [x] Implement new IntroScreen class and for the INTRO screenType - 03/10
- [x] Implement ScreenDisplay class to display stage containing buttons and intro scenes - 04/10
- [x] Update Documentation  - 04/10

## Documentation 
- [Game Intro](https://github.com/UQdeco2800/2021-studio-3/wiki/Game-Intro)

**Comment by K0zzas17** [comment]
We forgot to input this feature earlier; despite the program / design work being done, we believe it was still relevant to add it to GitHub.
