### ISSUE TITLE
Design the win screen appearing on a won game

### ISSUE THREAD

**Issue by Rucens** [UQdeco2800/2021-studio-3#16]
# **Description**
**Task Name**: Design win screen appearing on a won game.
**Feature**: Win / Loss Conditions & Visualisation #8

The win screens will need to appear when the player,

- clears the level: reaches the right-most of the screen 

The win screen will be a pop-up with the Main Game Screen displayed behind them. It will showcase ability to

- Restart the game
- Go to Settings
- Go back to main menu
 
# **Milestones**
- [x] Design a sketch of the win screen(Aug. 20)
- [x] Design win screen based on sketch (Aug. 26)
- [x] Update wiki documentation(Aug 29)
 
**Completion Deadline:** Aug. 30
 
 
# **Documentation**
- [Wiki link](https://github.com/UQdeco2800/2021-studio-3/wiki/Loss-&-Win-In-Game-Menus)

 
# **Member**
- Wendy (@WendyW16 ) 
- Niko (@n1ko4fun )

**Comment by WendyW16** [comment]
![lose whole (1)](https://user-images.githubusercontent.com/88033083/131314183-3f051cae-3121-4e2d-a5fa-fdb90e093f35.png)

**Comment by WendyW16** [comment]
![well](https://user-images.githubusercontent.com/88033083/131314350-7289dde6-78b3-46d7-9ddc-99d5383fe9e9.png)
