### ISSUE TITLE
Death Monster Improvements

### ISSUE THREAD

**Issue by BasJW** [UQdeco2800/2021-studio-3#163]
# Description

Right now the same serpent is shared among all levels, and moves rather slow. Ideally, a visually different serpent is used for each level to differentiate each level further. Also, the serpent will move faster depending on what level it is, keeping the players on their toes.

# Dependencies

 - [ ] Animation frames for each serpent

# Milestones

**Goal 1 - Increase Serpent's Speed Each Level**
- [ ] Alter serpent's base speed for level 1
- [ ] Increment the speed for each level
- [ ] Conduct user tests for the serpents speed each level

**Goal 2 - Change Serpent Visuals For Each Level**
- [ ] Change serpent animations for each different level

# Documentation

[The Improvements are at the bottom of this page](https://github.com/UQdeco2800/2021-studio-3/wiki/Death-Wall-Monster_

# Member

Sebastian (@BasJW)

**Comment by default-jamc** [comment]
Hey BasJW, I just wanted to let you know I found a bug with the serpent.

If the player presses `Pause` and then `Continue`, the serpent will more often than not stop chasing the player (but the player still takes damage on collision). I noticed there's a closed bug ticket for this here (#184 ), but I wasn't sure if this had been pushed to main yet. There's a new ticket for it here, if it hasn't (#200 )
