### ISSUE TITLE
Increase Serpent Speed Each Level

### ISSUE THREAD

**Issue by BasJW** [UQdeco2800/2021-studio-3#168]
# Description

Currently, the serpent speed is rather slow and does not present much of a challenge. Changing this will allow the game to become more challenging and enjoyable for the users

# Dependency
Death Wall Monster #110

# Milestones
 - [x] Change base serpent speed for all levels
 - [x] Increment serpent speed each level (Speed increases each level)
 - [x] Carry out rigorous user testing to fine-tune serpent speed

# Member
Sebastian(@BasJW )
Kevin(@Dollar0712 )

**Comment by BasJW** [comment]
> Hi guys, I'm currently working on implementing the Level Two Terrain (#233 ) and I've found that the serpent is _incredibly_ fast with respect to the complexity of the map. I'll be pushing the new terrain later today so you can see what I mean, but I think the serpents' speed might need to increase a little slower for the game to be winnable. Just thought I'd give you a heads up! 🚀

Okay, well after you push we'll be happy to change the speeds to a normal level, thanks for the notice heads up !
