### ISSUE TITLE
Design the loss screen appearing on a lost game

### ISSUE THREAD

**Issue by Rucens** [UQdeco2800/2021-studio-3#17]
# **Description**
**Task Name**: Design loss screen appearing on a lost game.
**Feature**: Win / Loss Conditions & Visualisation #8

The loss screens will need to appear when the player,

- loses the level: their health reaches 0 

The loss screen will be a pop-up with the Main Game Screen displayed behind them. It will showcase ability to

- Restart the game
- Go to Settings
- Go back to main menu
 
# **Milestones**
- [x] Design a sketch of the loss screen(Aug. 20)
- [x] Design loss screen based on sketch (Aug. 26)
- [x] Update wiki documentation(Aug 29)
 
**Completion Deadline:** Aug. 30
 
 
# **Documentation**
- [Wiki link](https://github.com/UQdeco2800/2021-studio-3/wiki/Loss-&-Win-In-Game-Menus)

 
# **Member**
- Wendy (@WendyW16 ) 
- Niko (@n1ko4fun )

**Comment by WendyW16** [comment]
![lose whole (1)](https://user-images.githubusercontent.com/88033083/131314558-f9ad6a5b-0d54-409f-95be-56a3971e8abf.png)

**Comment by WendyW16** [comment]
![lose](https://user-images.githubusercontent.com/88033083/131314626-f5e7c1c2-f8ed-4d78-a8e0-4de40a8cd192.png)
