### ISSUE TITLE
Map Development & Extension

### ISSUE THREAD

**Issue by default-jamc** [UQdeco2800/2021-studio-3#170]
## **Description**
Currently, the game has only 3 levels with no linear increase in difficulty as the player progresses. The current levels are also very short, and can be completed in less than a minute if sprinting. These issues will be addressed by;

1. extending the current levels lengths,
2. adding an additional level, and
3. designing new terrain layouts so as to slowly introduce the player to all aspects of the game, and provide an increasing level of difficulty throughout the levels. 

There will be 4 levels implemented (in total). The current three will be changed as part of this feature.

### **Sub-feature / Components**
- Determining the new terrain layout
- Designing the new terrain's visual aspects (floor, underground, sky)
- Placement of obstacles and enemies on the levels

## **Dependencies**
- The complete integration of all of the new levels will rely on the completion and integration of the tutorial level.

## **Milestones**

**Tasks**

- [x] Create wiki documentation (Oct. 7)
- [x] Research common platformers and side-scrollers to gain insight into map development. (@default-jamc) (Oct. 8)
- [x] Increase the current map count to have four playable levels (@default-jamc) (#171 ) (Oct. 9)
- [x] Overhaul of Level System (@default-jamc ) (#179 ) (Oct. 9)
- [x] Extend the current map file read implementation to work for all 3 elements of the map (floor, sky, underground) (@raneechu) (#197 ) (Oct. 10)
- [x] Determine the goal & purpose of every level (@default-jamc  ) (Oct. 10)
    - [x] Level of difficulty 
    - [x] Purposeful enemy placement
    - [x] Lesson player is learning on the level (eg, how to use certain movements)
- [ ] Make changes to player roll which allow it to properly benefit the player in the new maps (@raneechu  ) (#196 ) (Oct. 14)
- [x] Design & implement new level terrain (Oct. 15)
    - [x] Level One (@default-jamc ) (#199 )
    - [x] Level Two (@default-jamc ) (#233 )
    - [x] Level Three (@default-jamc ) (#240 )
    - [x] Level Four (@default-jamc ) (#241 )
- [x] Add 'floating elements' to the new maps (@default-jamc ) (#243 ) (Oct. 16)
- [x] Design the new level terrain (@WendyW16, @n1ko4fun) (#182 ) (Oct. 16)
   - [x] Sky tile design
   - [x] Underground tile design
   - [x] Floor tile design 

**Testing**
- [x] Complete user & play-testing to determine suitability of the level terrain (Oct. 17)
- [x] Complete user testing for the terrain's visual design (Oct. 17)
    - [x] Sky tile design
    - [x] Underground tile design
    - [x] Floor tile design 
- [x] JUnit testing (Oct. 17)
    - [x] `PopupMenuActions` (@default-jamc ) 
    - [x] `ForestGameArea` (@default-jamc )
    - [x] `LevelTwoArea` (@default-jamc )
    - [x] `LevelThreeArea` (@default-jamc )
    - [x] `LevelFourArea` (@default-jamc )

**Finalisation**
- [x] Update existing wiki documentation (Oct. 18)
- [x] Create UML / Sequence diagrams where relevant (Oct. 18)

______________________________________________________________________________________________________
**Completion Deadline:** Oct. 19

## **Documentation**
- [Gameplay Design Guide](https://github.com/UQdeco2800/2021-studio-3/wiki/Gameplay-Design-Guide)
- [Level Design Wiki Page](https://github.com/UQdeco2800/2021-studio-3/wiki/Level-Design)
- [Multiple game level](https://github.com/UQdeco2800/2021-studio-3/wiki/Multiple-game-level)

## **Members**
- Jazmin (@default-jamc)
- Niko (@n1ko4fun)
- Ranee (@raneechu)
- Su (@Su-LAN)
- Wendy (@WendyW16)

**Comment by default-jamc** [comment]
[07/10] _Changelog_ :
- Overhaul of Level System (#179 ) was added to the **Milestones**.

**Comment by default-jamc** [comment]
[08/10] _Changelog_:

- Added the [Gameplay Design Guide](https://github.com/UQdeco2800/2021-studio-3/wiki/Gameplay-Design-Guide) to the **Documentation**

**Comment by default-jamc** [comment]
[15/10] _Changelog:_
- Added the task "_Design & Implement Level Two_" (#233 )

**Comment by ShiyanSu** [comment]
Hi, guys. I will finish all the implementation of the enemies today. I'd like to work with you guys to reset the attack modes for the enemies includes attacking range, response time, bullet speed and the attack direction, in order to make them fit into new level design better. Just wondering if you guys have time to conduct a discussion about the final arrangement of the enemies.

**Comment by default-jamc** [comment]
[17/10] _Changelog:_
- Added `PopupMenuActions` to the JUnit testing **Milestone**.
- Linked the "_Design & Implement Level Two_" (#233 ) **Task**
- Linked the "_Design & Implement Level Three_" (#240 ) **Task**

**Comment by default-jamc** [comment]
Okay. The level design is complete but I will try to work the moving platforms in, as they're an interesting obstacle :). Also I think the current enemies (UFO, Robot, Asteroid Fire) do a little too much damage for how fast the serpent is going, and how difficult the levels become. This can all be scaled once it's all pushed together. 🚀
