### ISSUE TITLE
Implementation of Fourth Level

### ISSUE THREAD

**Issue by default-jamc** [UQdeco2800/2021-studio-3#171]
# Description
**Task Name:** Implementation of Fourth Level.
**Feature:** Map Development & Extension #170 

Currently, the game only has three playable levels. However, for the final iteration we would like there to be four to allow for more granularity in the range of difficulty for the player.

The implementation of the fourth level will make changes to the `ForestGameArea`, `LevelTwo`, and `LevelThree` classes. Another class `LevelFour` will likely be created as part of this task too.

# Milestones
- [x] Read current implementation of multiple levels (Oct. 8)
- [x] Extend the current implementation to include a fourth level.
- [x] Ensure all dependent functionality continues to function as expected
- [x] Update Map Extension Wiki documentation (Oct. 9)

# Extras
- [x] Fix the multi-level buff spawning bug (@default-jamc ) (#178 )
- [x] Fix the lives not reducing bug (@K0zzas17 ) (#183 )

**Completion Deadline:** Oct. 9

# Documentation
- [Level Design Wiki Page](https://github.com/UQdeco2800/2021-studio-3/wiki/Level-Design)
- [Multiple game level Wiki Page](https://github.com/UQdeco2800/2021-studio-3/wiki/Multiple-game-level)

# Member
- Jazmin (@default-jamc)

**Comment by default-jamc** [comment]
[14/10] _Changelog_:

- The "Complete additional JUnit testing" **Milestone** was removed as it is covered in (#170 )
