### ISSUE TITLE
Load Implementation

### ISSUE THREAD

**Issue by K0zzas17** [UQdeco2800/2021-studio-3#174]
# Description
**Task Name:** Load Implementation
**Feature:** Design Load and Save System #166 

This task represents the final half of Ticket #166; loading the player data from the save file. After saving the progress and leaving the game, the player will need to access their save file from the menu. Currently, implementation is conducted with the ideology of a single save file, however this may change down the line. For now, the load implementation will simply be tasked of finding this save file, reading the parameters, and recreating a new game instance based on these designations. 

Classes updated will be the same as in ticket #173. Modification to the `LoadingScreenDisplay` class may also be necessary.

# Milestones
- [x] Update Documentation
- [x] Update necessary classes for implementation
- [x] Design a system to read the game save file
- [x] Implement starting a new game instance with the predefined player characteristics saved.
- [x] Update Documentation

# Documentation 
- [Save and Load System](https://github.com/UQdeco2800/2021-studio-3/wiki/Save-and-Load-System)
