### ISSUE TITLE
Improve Score System

### ISSUE THREAD

**Issue by yeegoh** [UQdeco2800/2021-studio-3#176]
# Description
Issues with player metrics will be addressed and improved. This will include making the scoring system more complex by incorporating the addition of buffs. 

# Dependencies

# Milestones
- [ ] Improve complexity of the score
- [ ] Improve step count metric
- [ ] Update wiki documentation

# Documentation
