### ISSUE TITLE
Updating Menu and Popup Screen designs

### ISSUE THREAD

**Issue by yeegoh** [UQdeco2800/2021-studio-3#177]
# Description
The custom win and loss screens will be updated according to the changes made in the game. This includes creating a new "Continue?" screen for when the player loses a life, and then using the existing "You Died!" screen to display when the player loses all lives and must restart the game. This will help distinguish the different win/loss conditions, which were previously playing the same screens. 

# Dependencies
Design Custom Loss Screens #43 

# Milestones
- [x] Redesign custom death screens
- [x] Design restart screen when the player has lost all lives
- [x] Design win screen upon game completion
- [x] Update wiki documentation

# Documentation
[Loss & Win In Game Menus](https://github.com/UQdeco2800/2021-studio-3/wiki/Loss-%26-Win-In-Game-Menus)
