### ISSUE TITLE
Buffs & Debuffs not spawning on Levels Two & Three Bug

### ISSUE THREAD

**Issue by default-jamc** [UQdeco2800/2021-studio-3#178]
# Description
With the addition of multiple maps in the previous sprint, the spawning and despawning of buffs was not maintained across the additional levels (Level Two, Level Three). 

This bug will be fixed by ensuring that the additional levels account for the creation and handling of a `BuffManager`, and that the `BuffManager` class handles multiple levels.

**Related Task**:  (#171)

# Milestones
- [x] Update current multiple-level implementation to handle buff spawning
- [x] Ensure `BuffManager` functions correctly with the new implementation
- [x] Ensure all dependent functionality continues to work as intended
- [x] Complete JUnit and / or functional testing

# Members
Jazmin (@default-jamc)
