### ISSUE TITLE
Overhaul of Level System

### ISSUE THREAD

**Issue by default-jamc** [UQdeco2800/2021-studio-3#179]
# Description
**Task Name:** Overhaul of Level System.
**Feature:** Map Development & Extension #170 

The current levelling system has a lot of duplicate code, making it difficult to extend and alter. The implementation will be re-worked to remove the duplication in the `Area` and `Screen` classes. This overhaul may also facilitate the completion of #178 .

The overhaul will make changes to the `ForestGameArea`, `LevelTwoArea`, `LevelThreeArea`, `LevelTwoScreen` and `LevelThreeScreen` classes. Other moderately affected classes (eg, `PopupMenuActions`) will also be changed. 

# Milestones
- [x] Overhaul of `Areas` classes
    - [x] `LevelTwoArea` 
    - [x] `LevelThreeArea`
- [x] Overhaul of `Screens` classes
    - [x] `LevelTwoScreen`
    - [x] `LevelThreeScreen` 
- [x] Clean up other classes with duplicate code
    - [x] `PopupMenuActions`
    - ~`CheckPointComponent`~
- [x] Ensure all dependent code continues to work as intended

# Extras
- [x] Fix the multi-level buff spawning bug (@default-jamc ) (#178 )
- [x] Fix the lives not reducing bug (@K0zzas17 ) (#183 )

**Completion Deadline:** Oct. 10

# Documentation
- [*Not yet written*](https://github.com/UQdeco2800/2021-studio-3/wiki/)

# Member
- Jazmin (@default-jamc)

**Comment by ShiyanSu** [comment]
Hi, Jaz. When I implemented the multi-level function, I found that the buffs could not be disposed at all when generating the new area in a same screen. Therefore, I chose to implement the screen for each level and I think the easiest way to do the multi-level is to remain the current implementation and just add the construction methods of the buffs for the new areas . If you need any help with the multi-level, I am happy to help.

**Comment by default-jamc** [comment]
Hey Shiyan, thanks for the heads up. I'm working on the screens today, and it is likely I will keep them separated and create a `LevelFourScreen` :)
