### ISSUE TITLE
Implement HUD progress tracker & Functionality

### ISSUE THREAD

**Issue by K0zzas17** [UQdeco2800/2021-studio-3#18]
# Description
Implement the progress tracker on the HUD, so that it is visible at all times to the player. This will look like a bar that increments as the player moves forward and overcomes obstacles, with it finishing at 100% when the level is finished. This information will be used on the death screen (show players where they died) and the pause screen (show level of completion to that point.)

# Dependencies
- The death / win screen #8 will need to be implemented for full completion, no dependencies for HUD functionality.
- Font style to be referenced from HUD design
- Issue #6 will need to be completed in order for functionality to be implement (i.e. tracker monitors player's x-axis progress)

# Milestones
- [x] Add to Progress Tracker wiki (Aug 23)
- [x] Create HUD overlay concept (Aug 24)
- [x] Implement % of completed progressed to the loss and pause menu screens (Aug 25)
- [x] Create the `ProgressComponent` class (Aug 25)
- [x] Write JUnit Tests (28 Aug)
- [x] Implement Progress bar into HUD (Aug 29)
- [x] Update Wiki Documentation (30 Aug)
