### ISSUE TITLE
Current boss enemies improvements and new types of enemies implementation

### ISSUE THREAD

**Issue by ShiyanSu** [UQdeco2800/2021-studio-3#180]
## Description 
At this stage, there are three different types of boss enemies that are the alien monster, alien soldier and the alien boss. However, some bugs still exist such as when the player jumps on top of the enemy, the enemy will move down until reach the floor. Also, the current attack response time and the attack range of the enemies should be changed to make them more functional and increase the difficulty of the game. In addition, the animation effects should be added to the enemies at this point.
As there will be more levels generated during this sprint, we should also implement new types of enemies that have different appearances and attack methods (e.g. continuously shoot the bullets horizontally). 

## Examples

1. After changing the attack range of enemies, some of they may can make a full map attack.

## Dependencies

- The overall change for the attack response time and the attack range of the boss enemies will depend on the final settings of each level.

## Milestones

- [x] Adjust and finalize three old enemies animation design (Oct. 9th)
- [x] Fix the bugs for the previous three types of enemies (Oct. 9th) 
- [x] Re-implement the attack response time and attack range for the previous three enemies (Oct. 9th) 
- [x] Add the speed changing function to enemies' bullets and adjust the speed (Oct. 10th) #212 
- [x] Implement new types of enemies (Oct. 10th) #223 #224 
- [x] Add the animation effects to all the enemies (Oct. 10th) #221 
- [x] Write JUnit test for the new enemies (Oct. 11th)
- [x] Design new enemies and bullets (Oct. 14th) #205 
- [x] Add two new enemies animation (Oct. 15th) #208 
- [x] Put new enemies design in the game (Oct. 16th)
- [x] Update the wiki document for enemies (Oct. 16th) #205 

## Documentation 

- [Wiki for Boss Enemies](https://github.com/UQdeco2800/2021-studio-3/wiki/Boss-enemies)
- [Wiki for Enemy animation](https://github.com/UQdeco2800/2021-studio-3/wiki/Boss-enemies-animation)

## Members 

- Shiyan Su(@ShiyanSu)
- Zhiyuan Xu(@DLAmeng)
- Emily Zeng(@emily-dl)
- Tom Mann(@44806158)

**Comment by default-jamc** [comment]
Hi guys! I've finished implementing the fourth level. Since my implementation changed some (very slight) things, I just wanted to let you know that I'm going to make some changes to your [Multiple Game Levels wiki page](https://github.com/UQdeco2800/2021-studio-3/wiki/Multiple-game-level). I won't remove anything, just make some changes to reflect the new implementation :)
