### ISSUE TITLE
Design additional sound effects 

### ISSUE THREAD

**Issue by emily-dl** [UQdeco2800/2021-studio-3#181]
# Description 
Task: Help team 3 design extra sound effects, including game story background sound, loading screen sound, new level 4 sound and win condition sound.

# Milestones
- [ ] Design two sound effects for each game scene 08/10
- [ ] Test the sound and ask 5 testees to choose their preferences 09/10
- [ ] Finalize the sound design

# Documentation
