### ISSUE TITLE
Design the new level terrain

### ISSUE THREAD

**Issue by WendyW16** [UQdeco2800/2021-studio-3#182]
# Description
**Task Name:** Design the new level terrain
**Feature:** Map Development & Extension #170 

With the addition of a fourth level, new terrain will need to be designed to indicate to the player that they have entered a new area. The new terrain's visual aspects (floor, underground, sky) will be designed as part of this task.

## **Dependencies**
- The complete integration of all of the new levels will rely on the completion and integration of the tutorial level.

## **Milestones**
- [x] Sky tile design (Oct. 14)
- [x] Underground tile design (Oct. 15) 
- [x]  Floor tile design (Oct. 15)
- [x] Complete user & play-testing to determine the suitability of the level terrain (Oct. 16)
- [x] Complete user testing for the terrain's visual design (Oct. 17)
- [x] Update existing wiki documentation (Oct. 18)

**Completion Deadline:** Oct. 19

## **Documentation**
- [Gameplay Design Guide](https://github.com/UQdeco2800/2021-studio-3/wiki/Gameplay-Design-Guide)
- [Level Design Wiki Page](https://github.com/UQdeco2800/2021-studio-3/wiki/Level-Design)
- [Multiple game level](https://github.com/UQdeco2800/2021-studio-3/wiki/Multiple-game-level)

## **Members**
- Wendy (@WendyW16)
- Niko (@n1ko4fun)
