### ISSUE TITLE
Implementing the spaceship into the last level

### ISSUE THREAD

**Issue by SirAardvark** [UQdeco2800/2021-studio-3#186]
## Description
Feature: Player reaching end of last level animations #73

Once the spaceship is made with an atlas file. It will need to be added into the final level 

## Dependencies 
The spaceship to be made and with an atlas animation (Ticket #185)

## Milestones
- [ ] Edit the final wall to not pop up with the player win screen
- [ ] Make a new entity for the spaceship that the player can interact with (Use a place holder atlas until spaceship is done)
- [ ] Place the spaceship at the end of the last map
- [ ] Apply the spaceship textures and animations
- [ ] Once the player interacts with it, stop the dragon from moving, make the player not take damage, make the player walk into the spaceship, start the flying animation.
- [ ] Ask other members to try it before pushing to main
- [ ] Make a Wiki Page for it

## Members
Justin (@SirAardvark )

**Comment by ShiyanSu** [comment]
Hi, guys. Our team has finished the design of the sound effects for the win actions. Just wondering when you guys will finish this task and merge it to main. And then we could add the sound effects for it.

**Comment by SirAardvark** [comment]
Hey @ShiyanSu it is currently in a pull request. I'm just waiting for someone from my team to test it and approve it. If you want to approve it you can by pulling levelTransitions and testing that they work.

Here is the pull request.
https://github.com/UQdeco2800/2021-studio-3/pull/238
