### ISSUE TITLE
Implement the portals

### ISSUE THREAD

**Issue by SirAardvark** [UQdeco2800/2021-studio-3#189]
## Description
Feature: Portal transition between levels #164

## Dependencies
The portals need to be made with an atlas animation (Ticket #187)

## Milestones
- [x] Make a new entity for the portal (Use random texture until portal is made)
- [x] Make the invisible wall not trigger the next level
- [x] Add the portal to the end of the level
- [x] Apply the portal textures and animations
- [x] Once the player interacts with it start the load screen
- [x] Change the load screen to show the player and dragon walking through the portal
- [ ] Ask other members to try it before pushing to main
- [ ] Make a Wiki Page for it

## Documentation
Updated Wiki:
https://github.com/UQdeco2800/2021-studio-3/wiki/Obstacles
## Members
Justin (@SirAardvark)

**Comment by SirAardvark** [comment]
Added the portal with a tree texture, player can walk into in it to start the next level.

I spoke with team 3 on Discord and they suggested I use there dynamic y-position placer they use for their buffs. The portal will now spawn at the end of the map and in the correct y-position regardless of the map.

Once the textures are made they will be added in.

Pushes:
- Added the tree textured portals that spawns in the correct x-position (2873ded07b3cb1a6347974453916924d52d04d44)
- Added team 3's dynamic y-positioning (3f56a59f685167f87f053dbe81b6371409a39db0)

![image](https://user-images.githubusercontent.com/69832032/136680068-c27db13d-1d8c-4a67-8821-381341ebf35e.png)
