### ISSUE TITLE
Implement dynamic HP (Hit Points) Bar

### ISSUE THREAD

**Issue by default-jamc** [UQdeco2800/2021-studio-3#19]
# Description
**Task Name:** Implement dynamic HP (Hit Points) bar.
**Feature:** Win / Loss Conditions & Visualisation #8 

The player will have a dynamic HP bar that will update as their health decreases, or increases. The HP bar will either; 
- sit above the players' head, making it a `UIComponent` of the `player` or, 
- be shown in the top-left corner of the screen, on the `PlayerStatsDisplay` UI.
- The HP is base on the percentage.

# Milestones
- [x] Create class for `PlayerHealthBar` (Aug. 27)
- [x] Create `Event` to trigger the update of the `PlayerHealthBar` (Aug. 29)
- [x] Update Wiki documentation (Aug. 30)

**Completion Deadline:** Aug. 31

# Documentation
- [Wiki page](https://github.com/UQdeco2800/2021-studio-3/wiki/Player-UI)

# Member
- SU (@Su-LAN)

**Comment by Su-LAN** [comment]
https://user-images.githubusercontent.com/88018784/130726356-0e0ac1b3-2c4b-423f-b653-bc36c44a6bbc.mov

![Screen Shot 2021-08-24 at 1 33 05 pm](https://user-images.githubusercontent.com/88018784/130726370-dcba5bdc-e5d2-43e5-b47a-2aae2c356cb6.png)
![Screen Shot 2021-08-24 at 1 33 18 pm](https://user-images.githubusercontent.com/88018784/130726371-ff84fb30-16be-4676-88dd-a4a28dcc61b6.png)
![Screen Shot 2021-08-24 at 1 33 20 pm](https://user-images.githubusercontent.com/88018784/130726372-dff22688-070c-4419-a828-4de91c640771.png)
![Screen Shot 2021-08-24 at 1 33 21 pm](https://user-images.githubusercontent.com/88018784/130726374-8ef0789b-dd3c-40bc-81a4-e14ca5ab5b61.png)
![Screen Shot 2021-08-24 at 1 33 22 pm](https://user-images.githubusercontent.com/88018784/130726375-2f8bf373-95a4-47c7-b14c-bb401ae368d6.png)
![Screen Shot 2021-08-24 at 1 33 28 pm](https://user-images.githubusercontent.com/88018784/130726377-b5465280-58b5-482a-9bbd-24a47f22f01e.png)
![Screen Shot 2021-08-24 at 1 33 30 pm](https://user-images.githubusercontent.com/88018784/130726378-8d0cc574-9cae-4b20-a823-499146aab80b.png)
![Screen Shot 2021-08-24 at 1 33 31 pm](https://user-images.githubusercontent.com/88018784/130726379-e316d276-3537-4cbe-86ef-42aa24f07e92.png)
![Screen Shot 2021-08-24 at 1 33 32 pm](https://user-images.githubusercontent.com/88018784/130726381-d4576af1-bc4a-458e-90ce-bfb486788e6d.png)
![Screen Shot 2021-08-24 at 1 33 33 pm](https://user-images.githubusercontent.com/88018784/130726382-ed82f9cd-1fc6-42f4-83a9-8dcaf7d24dd9.png)
![Screen Shot 2021-08-24 at 1 33 35 pm](https://user-images.githubusercontent.com/88018784/130726383-487ac9c0-c66d-45b1-a975-eb0bf6e7b391.png)

**Comment by K0zzas17** [comment]
Hi Guys! how did you come up with the design for the dynamic HP bar?? I'm thinking of doing something similar with the level progress bar, but we're a bit unsure on how to come up with images you used. Thanks :))

**Comment by Su-LAN** [comment]
> # 描述
> **任务名称：**实现动态 HP（Hit Points）条。
> **功能：**赢/输条件和可视化#8
> 
> 玩家将拥有一个动态的 HP 条，该条会随着他们的健康减少或增加而更新。HP 条会；
> 
> * 坐在球员的头顶，使之成为`UIComponent`的`player`，或者
> * 显示在屏幕的左上角，在`PlayerStatsDisplay`UI 上。
> * HP 是基于百分比。
> 
> # 里程碑
> * [x] 创建课程`PlayerHealthBar`（8 月 27 日）
> * [x] 创建`Event`触发更新`PlayerHealthBar`（8月29日）
> * [x]  更新 Wiki 文档（8 月 30 日）
> 
> **完成截止日期：** 8 月 31 日
> 
> # 文档
> * [维基页面](https://github.com/UQdeco2800/2021-studio-3/wiki/Player-UI)
> 
> # 成员
> * 苏 ( @Su-LAN )
