### ISSUE TITLE
Optimise TerrainFactory

### ISSUE THREAD

**Issue by raneechu** [UQdeco2800/2021-studio-3#197]
# Description
**Task Name:** Optimise TerrainFactory
**Feature:** Map Development & Extension #170 

The current `TerrainFactory` has copious lines of tedious code when filling out the tiles on the map. Thus, the information regarding the gridpoints of different tiles will be moved to a text file, similar to how the underground and surface tiles are currently filled out. 

Changes will be made by adding a helper method which reads the lines of the text file, a method to fill in the sky tiles and a method to fill in the floor tiles.

# Milestones
- [x] Write method to read text files
- [x] Write method to fill in sky tiles
- [x] Write method to fill in floor tiles
- [x] Documentation

**Completion Deadline:** Oct. 12

# Documentation
- [Game Background](https://github.com/UQdeco2800/2021-studio-3/wiki/Game-Background)

# Member
- Ranee (@raneechu)
