### ISSUE TITLE
Design outro screens for the ending of the game

### ISSUE THREAD

**Issue by sh4453** [UQdeco2800/2021-studio-3#198]
# Description 
Task: Design outro screens for the ending of the game 
Feature: #162 

This task will involve wrapping up the story and creating an ending sequence for the player once they have beaten all of the levels and finished the game. This will give a sense of completion for the player, and also a definite conclusion to the game as opposed to just another pop-up menu. 

# Dependencies 
- [ ] Outro screen story needs to line up with what happens in the last level animation #185 

# Milestones
- [x]  Sketch out draft scenes (9 sept)
- [x]  Design on Illustrator (10 sept)
- [x] User testing (14 sept)
- [x] Update wiki documentation (16 sept)

# Documentation 
[Game Outro Wiki Page](https://github.com/UQdeco2800/2021-studio-3/wiki/Game-Outro)

# Member 
Sarah Han (@sh4453)
