### ISSUE TITLE
Design & Implement Level One

### ISSUE THREAD

**Issue by default-jamc** [UQdeco2800/2021-studio-3#199]
# Description
**Task Name:** Design Level One
**Feature:** Map Development & Extension #170 

With the new map development, four levels need to be designed. This includes the environmental hazards and object placement. This task pertains to the development of the first level.

# Milestones
- [x] Sketch the map layout (Oct. 12)
- [x] Get user feedback (Oct. 12)
- [x] Implement into the game (Oct. 15)
- ~Perform user tests to determine suitability (Oct. 16)~

**Completion Deadline:** Oct. 16

# Documentation
- [Level Design Wiki Page](https://github.com/UQdeco2800/2021-studio-3/wiki/Level-Design)

# Member
- Jazmin (@default-jamc )
