### ISSUE TITLE
Implement the static obstacle - Asteroid

### ISSUE THREAD

**Issue by ShiyanSu** [UQdeco2800/2021-studio-3#20]
# Description
**Task Name:** Implement the static obstacle - Asteroid 
**Feature:** Obstacle Feature 

The static obstacle asteroid should appear once the player starts the game and the position of each asteroid should remain stable within the game. For those asteroids on the map, the player cannot directly pass through them. In order to move forward, the player have to jump over these asteroids.

# Dependencies
- [x] Static obstacle - asteroid should be designed

# Milestones
- [x] Implement createAsteroid function to create the asteroid obstacle in the ObstacleFactory class (Aug. 24)
- [x] Create spawnAsteroid function inside the ForestGameArea class (Aug. 24)
- [x] Adjust the position of the asteroid within the map and integrate into the game  (Aug. 26)
- [x] Update Wiki documentation (Aug. 26)

**Completion Deadline:** Aug.26

# Member
- Shiyan Su (@ShiyanSu)
- Zhiyuan Xu (@DLAmeng)
