### ISSUE TITLE
Design two new enemies

### ISSUE THREAD

**Issue by emily-dl** [UQdeco2800/2021-studio-3#205]
# Description 
Task: As the studio decides to add one new level to the final game, we need to design two new alien enemies. The first one shoots bullets from right to left and the second attack the player with harmful lasers when the player approaches.

# Milestones
- [x] Design draft version of two new enemies 14/10
- [x] Design one enemy's bullet and one enemy's laser weapon (colour transition) 14/10
- [x] Draft enemies user testing 15/10
- [x] Finalize the enemy design 15/10
- [x] Update the enemy Wiki documentation 16/10

# Documentation
https://github.com/UQdeco2800/2021-studio-3/wiki/Boss-enemies
