### ISSUE TITLE
Player lives reset upon entering a new level

### ISSUE THREAD

**Issue by K0zzas17** [UQdeco2800/2021-studio-3#206]
# Description
When the player hits the next level button, the player starts a new reset level where all previous stats are erased and reset.

This bug will be fixed by allow the player entity data to be saved and recreated upon starting a new level.

# Milestones
- [ ] Update current player creation on a new level
- [ ] Update necessary classes to allow a player input
- [ ] Update Documentation as necessary
- [ ] Complete a JUnit or functional test to ensure appropriate functionality remains
