### ISSUE TITLE
Design new enemies animation 

### ISSUE THREAD

**Issue by emily-dl** [UQdeco2800/2021-studio-3#208]
# Description 
Task: Design the animation for two new enemies

# Milestones
- [ ] Design the animation for first enemy 14/10
- [ ] Design the animation for second enemy 15/10
- [ ] Update the enemy wiki document  16/10

# Documentation
