### ISSUE TITLE
Designing checkpoint and progress bar visuals 

### ISSUE THREAD

**Issue by sh4453** [UQdeco2800/2021-studio-3#21]
### Description
Designing checkpoint icons and item menu 
Feature: #9 

Visual cue for the player to know that they have passed the halfway point. Icons for each level and section to be placed at each checkpoint. Decided to make it a rover with viking influence, to keep in line with the space theme, and each checkpoint will have a rover with a different colour scheme. 

Icon to place on progress bar to show player that they have reached a certain point on the level overall. Decided to make it a meteor to keep in line with the space theme 

### Milestone

- [x] Sketch out rough drafts of the checkpoints and menu - 23/8
- [x] Confirm with win/loss and obstacles what the aesthetic will look like - 25/8
- [x] Make solid design for rover and meteor on illustrator - 25/8
- [x] Colour and send to team - 29/8
- [x] Incorporate viking influence into the rover- 29/8
- [x] Get #19 HP bar designs for our progress bar design - 29/8 
- [x] Edit wiki documentation 30/8

### Member
@sh4453
