### ISSUE TITLE
Add speed changing function to enemy's bullet and adjust the moving speed of bullets for enemies

### ISSUE THREAD

**Issue by ShiyanSu** [UQdeco2800/2021-studio-3#212]
# Description
**Task Name:** Add speed changing function to enemy's bullet and adjust the moving speed of bullets for enemies.
**Feature:** Current boss enemies improvements and new types of enemies implementation
In order to make the enemies more meaningful and could adapt to the new game level design that has various difficulty settings, we are going to implement the function that could allow us to change the moving speed of the bullet and adjust the moving speed of bullets for each enemy according to the final level design.

# Dependencies

Before finally adjusting the bullet speed for each enemy, two things that must be done:

- Implementation of two new types of enemies.
- Final game level design #170 .

# Milestone

- [x] Create the function in `PhysicsMovementComponent` class to change the moving velocity of bullet entity (Oct. 13th)
- [x] Adjust the moving speed of bullets for all the enemies (Oct. )
- [x] Update Wiki (Oct. 15th)

# Member

- Shiyan Su (@ShiyanSu)
