### ISSUE TITLE
Player Animations

### ISSUE THREAD

**Issue by ShahM1h1r** [UQdeco2800/2021-studio-3#22]
**Task: Player Animation
Feature: Additional Player Movement & Animation**

We will be creating the animations for the Jump, Walk, Damage, and Sprint. The damage animation will show the changes in visual appearance of the character in 20% health intervals. 

**Example** 
When the character health drops to 80% the character will have ripped clothes.

**Dependencies**
Character Feature Ticket (#33)

**Milestones**
List of steps that need to be completed for this task.

- [x] Jump Frames (Aug. 29)
- [x] Walk Frames (Aug. 29)
- [x] Sprint Frames (Aug 29)
- [x] Damage Frames (Aug. 29)

Completion Deadline: Aug. 29

**Documentation**
Character Design Guide

**Member**
Mihir (@ShahM1h1r )
Paul (@paulchoi610 )
