### ISSUE TITLE
Implement the animation effect for all the enemies

### ISSUE THREAD

**Issue by ShiyanSu** [UQdeco2800/2021-studio-3#221]
# Description
**Task Name:** Implement the animation effect for all the enemies
**Feature:** Current boss enemies improvements and new types of enemies implementation

Implement the animation effect for all 5 types of enemies to make them more interactive and bring better visual experience to the player.

# Dependencies
- [x] Animation effects and images of enemies- should be designed

# Milestones

- [x] Implement the animation effect for alien soldier enemy (Oct. 14th)
    - [x] Write the `alienSoldier.atlas` to create the animation for alien s (OCt. 14)
    - [x] Add the animation to `createAlienSoldier()` function in the `EnemyFactory` class (Oct. 14)
- [x] Implement the animation effect for alien monster enemy (Oct. 14th)
    - [x] Write the `alienMonster.atlas` to create the animation for alien s (OCt. 14)
    - [x] Add the animation to `createAlienMonster()` function in the `EnemyFactory` class (Oct. 14)
- [x] Implement the animation effect for alien boss enemy (Oct. 14th)
    - [x] Write the `alienBoss.atlas` to create the animation for alien s (OCt. 14)
    - [x] Add the animation to `createAlienBoss()` function in the `EnemyFactory` class (Oct. 14)
- [x] Implement the animation effect for alien barbette enemy (Oct. 14th)
    - [x] Write the `alienBarbette.atlas` to create the animation for alien s (OCt. 14)
    - [x] Add the animation to `createAlienBarbette()` function in the `EnemyFactory` class (Oct. 14)
- [x] Implement the animation effect for alien laser hole enemy (Oct. 14th)
    - [x] Write the `alienLaserHole.atlas` to create the animation for alien s (OCt. 14)
    - [x] Add the animation to `createAlienLaserHole()` function in the `EnemyFactory` class (Oct. 14)
- [x] Update Wiki documentation (Oct. 15th) [Wiki for enemy animation](https://github.com/UQdeco2800/2021-studio-3/wiki/Boss-enemies-animation)

**Completion Deadline:** Oct. 15th

# Member
- Shiyan Su (@ShiyanSu)
