### ISSUE TITLE
Implement the new enemy - Alien Barbette

### ISSUE THREAD

**Issue by ShiyanSu** [UQdeco2800/2021-studio-3#223]
# Description
**Task Name:** Implement the new enemy - alien barbette
**Feature:** Current boss enemies improvements and new types of enemies implementation

Implement the new type of enemies named alien barbette. It is a static enemy that stays at a fixed position on the game map. The attack modes of this enemy are:

1. Shoot bullets from right to the left continuously.
2. The bullets should move horizontally and at a relatively fast speed.

# Dependencies
- [x] The image of enemy and its bullet - should be designed

# Milestones

- [x] Create the `AlienBarbetteAttackListener` class (Oct. 13th)
- [x] Implement `createAlienBarbette` function to create the Alien Barbette enemy in the EnemyFactory class (Oct. 13th)
- [x] Implement `createAlienBarbetteWeapon` function to create the bullet of Alien Soldier enemy in the EnemyFactory class (Oct. 13th)
- [x] Create `spawnAlienBarbette` function inside the each game area class (Oct. 14th)
- [x] Adjust the position of the Alien Boss within the map and integrate into the game (Oct. 15th)
- [x] Update Wiki documentation (Oct. 15th) [Updated Wiki for enemy](https://github.com/UQdeco2800/2021-studio-3/wiki/Boss-enemies)

**Completion Deadline:** Oct. 15th

# Member
- Shiyan Su (@ShiyanSu)

**Comment by default-jamc** [comment]
Hey @ShiyanSu, I'm currently working on developing the Level One terrain and it features this enemy. I've placed it into the map and it isn't shooting horizontally; it shoots slightly upwards. I saw in the demo on Wednesday that it did shoot horizontally on the old map. I'm not sure what is causing this bug, but I thought I would let you know. Thanks 🚀

**Comment by default-jamc** [comment]
Hey @ShiyanSu, I've just spawned another one into the level and this one shoots slightly downwards. It seems like it's possible that the angle the Barbette shoots at is influenced by the players' initial spawn position.

**Comment by default-jamc** [comment]
Hey @ShiyanSu , Just wanted to let you know that there's still a bug with this enemy (and the other enemies). I found it initially at the end of the last sprint (#146 ) and unfortunately it is still happening. In the meantime, I have replaced the enemies that cause this bug with UFO's, as it is not causing the error to occur.
