### ISSUE TITLE
Implement the new enemy - Alien Laser Hole

### ISSUE THREAD

**Issue by ShiyanSu** [UQdeco2800/2021-studio-3#224]
# Description
**Task Name:** Implement the new enemy - alien laser hole
**Feature:** Current boss enemies improvements and new types of enemies implementation

Implement the new type of enemies named alien laser hole. It is a static enemy that stays at a fixed position on the game map. The attack modes of this enemy are:

1. Fire the laser beam at a constant time interval.
2. The laser beam should be fired vertically down to the bottom of the ground.

# Dependencies
- [x] The image of enemy and its laser beam - should be designed

# Milestones

- [x] Create the `AlienLaserAttackListener` class (Oct. 13th)
- [x] Implement `createAlienLaserHole` function to create the Alien Laser Hole enemy in the EnemyFactory class (Oct. 13th)
- [x] Implement `createAlienLaserHoleWeapon` function to create the laser of Alien Laser Hole enemy in the EnemyFactory class (Oct. 13th)
- [x] Create `spawnAlienLaserHole` function inside the each game area class (Oct. 14th)
- [x] Adjust the position of the Alien Laser Hole within the map and integrate into the game (Oct. 15th)
- [x] Update Wiki documentation (Oct. 15th)

**Completion Deadline:** Oct. 15th

# Member
- Shiyan Su (@ShiyanSu)
