### ISSUE TITLE
Design & Implement Level Two

### ISSUE THREAD

**Issue by default-jamc** [UQdeco2800/2021-studio-3#233]
# Description
**Task Name:** Design & Implement Level Two
**Feature:** Map Development & Extension #170 

With the new map development, four levels need to be designed. This includes the environmental hazards and object placement. This task pertains to the development of the second level.

# Milestones
- [x] Sketch the map layout (Oct. 15)
- [x] Get user feedback (Oct. 16)
- [x] Implement into the game (Oct. 17)

**Completion Deadline:** Oct. 17

# Documentation
- [Level Design Wiki Page](https://github.com/UQdeco2800/2021-studio-3/wiki/Level-Design)

# Member
- Jazmin (@default-jamc )
