### ISSUE TITLE
Design game background

### ISSUE THREAD

**Issue by yeegoh** [UQdeco2800/2021-studio-3#24]
# Description
**Task Name:** Design game background
**Feature:** Obstacle Feature #7 

A background graphic will be inserted and move in correlation with the game map.

# Milestones
- [x] Create planet and star graphics (24 Aug)
- [x] Design prototype background screens for game map (26 Aug)
- [x] Update Wiki documentation (30 Aug)

# Documentation
[Design Guide](https://github.com/UQdeco2800/2021-studio-3/wiki/Design-Guide)

# Members
- Yee Ping Goh (@yeegoh) (Yee Goh)

**Comment by yeegoh** [comment]
Feedback welcomed.
![background_draft](https://user-images.githubusercontent.com/70673799/131206036-003cae39-5256-480c-9c8e-facf47612fcc.png)

**Comment by default-jamc** [comment]
This looks really nice @yeegoh! :) I love the colours and minimalistic style.

**Comment by yeegoh** [comment]
New version with "nordic" influence
![long background](https://user-images.githubusercontent.com/70673799/131246552-73361cb7-3c71-435a-9e15-6ec1b4d0df49.png)
