### ISSUE TITLE
Add Floating Elements to Levels 1, 2, 3 and 4.

### ISSUE THREAD

**Issue by default-jamc** [UQdeco2800/2021-studio-3#243]
# Description
**Task Name:** Add 'floating elements' to the new levels
**Feature:** Map Development & Extension #170 

With the new map development, four levels were designed. Some of these levels have 'floating' pieces, to allow for tunneling (the player walking 'inside' the map) and bars (low enough that the player must roll underneath). 

These floating elements must be added to the new level terrains.

# Milestones
- [ ] Add Level One floating elements (Oct. 16)
- [ ] Add Level Two floating elements (Oct. 16)
- [ ] Add Level Three floating elements (Oct. 17)
- [ ] Add Level Four floating elements (Oct. 17)

**Completion Deadline:** Oct. 17

# Documentation
- [Level Design Wiki Page](https://github.com/UQdeco2800/2021-studio-3/wiki/Level-Design)

# Member
- Jazmin (@default-jamc )
