### ISSUE TITLE
Create altered serpent designs and animations for each level 

### ISSUE THREAD

**Issue by paulchoi610** [UQdeco2800/2021-studio-3#245]
# Description

For each progressing level, the serpent should induce a physical change to indicate an increased aggressiveness. These changes will be implemented with a mix of slight changes in the animations and visual design of the serpent. However, it is important that the serpent still looks the same at it's core for the continuation of the story between the levels (would not make sense if the serpent completely changes between levels). The level 1 serpent will just be the base model.

Implemented in Death Monster Improvements (#163) 

# Milestones

- [x] Research possible design changes

**Goal 1 - Change serpent visuals for level 2**
- [x] Create visual change to the serpent and create animation frames
- [x] Convert frames into GDX spritesheet and atlas

**Goal 2 - Change serpent visuals for level 3**
- [x] Create visual change to the serpent and create animation frames
- [x] Convert frames into GDX spritesheet and atlas

**Goal 3 - Change serpent visuals for level 4**
- [x] Create visual change to the serpent and create animation frames
- [x] Convert frames into GDX spritesheet and atlas

# Documentation
Serpent design change for each progressing level: https://github.com/UQdeco2800/2021-studio-3/wiki/Serpent-design-change-for-each-progressing-level

# Members
Paul (@paulchoi610)
