### ISSUE TITLE
Add the function of moving left and right to the platform

### ISSUE THREAD

**Issue by DLAmeng** [UQdeco2800/2021-studio-3#251]
# Description
**Task Name:** Platform movement.
**Feature:** Make the platform move left and right without being affected by players.

# Dependencies

- [ ] The image of new type platform - should be designed

# Milestones

- [ ] Create the `PlatformTask` class. (Oct. 13th)
- [ ] Implement `createPlatform3` function to create the moving platform in the `ObstacleFactory` class. (Oct. 14th)
- [ ] Update Wiki documentation. (Oct. 15th)

**Completion Deadline:** Oct. 15th

# Member

- Zhiyuan Xu @DLAmeng
