### ISSUE TITLE
Implement the background music for the loading screen

### ISSUE THREAD

**Issue by ShiyanSu** [UQdeco2800/2021-studio-3#253]
# Description 
Task Name: Implement the background music for the loading screen.
Feature Name: Rest game sound effects design and implementation 
In order to make the user happier and look forward to the game through the waiting time, the background music for the loading screen should be implemented.

# Milestones

- [ ] Add the .mp3 file for the loading screen background music to the assets (Oct. 11th)
- [ ] Add the background music for `LoadingScreen` class and `LoadingDisplay` class (Oct. 11th)
- [ ] Update wiki (Oct. 17th)
** Completion deadline: Oct. 17th **
# Members

- Shiyan Su (@ShiyanSu)
