### ISSUE TITLE
Implement the background music for the game intro story screen.

### ISSUE THREAD

**Issue by ShiyanSu** [UQdeco2800/2021-studio-3#254]
# Description 
Task Name: Implement the background music for the game intro story screen.
Feature Name: Rest game sound effects design and implementation 

To bring users a more immersive experience with the game intro story and make the story screen more attractive, the designed background music should be implemented for this screen.

# Milestones

- [x] Add the .mp3 file for the intro screen background music to the assets (Oct. 11th)
- [x] Add the background music for `IntroScreen` class and `IntroDisplay` class (Oct. 11th)
- [x] Update wiki (Oct. 17th)

**Completion deadline: Oct. 17th**

# Members

- Shiyan Su (@ShiyanSu)
