### ISSUE TITLE
Design the pause screen appearing on paused game

### ISSUE THREAD

**Issue by WendyW16** [UQdeco2800/2021-studio-3#26]
# **Description**
**Task Name**: Design pause screen appearing on a paused game.
**Feature**: Win / Loss Conditions & Visualisation #8

The pause screens will need to appear when the player,

- Pause the game via button 

The pause screen will be a pop-up with the Main Game Screen displayed behind them. It will showcase ability to

- Restart the game
- Resume the game
- Go to Settings
- Go back to main menu
 
# **Milestones**
- [x] Design a sketch of the pause screen(Aug. 20)
- [x] Design pause screen based on sketch (Aug. 27)
- [x] Update wiki documentation(Aug 29)
 
**Completion Deadline:** Aug. 30
 
 
# **Documentation**
- [Wiki link](https://github.com/UQdeco2800/2021-studio-3/wiki/Loss-&-Win-In-Game-Menus)

 
# **Member**
- Wendy (@WendyW16 )

**Comment by Su-LAN** [comment]
![2](https://user-images.githubusercontent.com/88018784/131209598-80612f0d-29ed-4ad7-aa48-7c4424d4d1d3.png)
![4](https://user-images.githubusercontent.com/88018784/131209600-69b31d5e-092b-4a57-933f-29b7817c1db2.png)
![5](https://user-images.githubusercontent.com/88018784/131209601-df2372e8-c149-4304-ad37-640a0aaae534.png)
![6](https://user-images.githubusercontent.com/88018784/131209602-33352531-03b2-4a56-b522-f8757d79a944.png)
![7](https://user-images.githubusercontent.com/88018784/131209603-39368bff-2208-43e3-b88f-8dc6dda1d1c1.png)
![9](https://user-images.githubusercontent.com/88018784/131209604-aa359705-0190-40de-830d-f7d225726848.png)
![board1](https://user-images.githubusercontent.com/88018784/131209606-23426d00-6fb8-401b-a2c9-3dd248c8129b.png)

**Comment by WendyW16** [comment]
![Artboard 25](https://user-images.githubusercontent.com/88033083/131310959-acd47468-bb49-4089-b879-7fd6635d7b14.png)

**Comment by WendyW16** [comment]
![pause](https://user-images.githubusercontent.com/88033083/131356141-4a1eb88b-097b-4445-a2ac-fcb863714bff.png)
