### ISSUE TITLE
Implement the static obstcle - Asteroid fire (aggressive)

### ISSUE THREAD

**Issue by ShiyanSu** [UQdeco2800/2021-studio-3#27]
# Description
**Task Name:** Implement the static obstacle - Asteroid fire
**Feature:** Obstacle Feature 

The static obstacle asteroid fire should appear once the player starts the game and the position of each asteroid should remain stable within the game. For those asteroid fire obstacles on the map, if the player touches them (inside of the attack range of the asteroid fire), the player's health will be reduced. Also, the player cannot directly pass through them and have to jump over them.

# Dependencies
- [x] Static obstacle - asteroid fire should be designed

# Milestones
- [x] Create obstacle.json to contain the configs of aggressive obstacles (Aug. 28)
- [x] Add the configs of asteroid fire into obstacle.json (Aug. 28)
- [x] Create the ObstacleConfig class (Aug. 28)
- [x] Create the AsteroidConfig class (Aug. 28)
- [x] Implement createAsteroidFire function to create the asteroid fire obstacle in the ObstacleFactory class (Aug. 28)
- [x] Create spawnAsteroidFire function inside the ForestGameArea class (Aug. 28)
- [x] Adjust the position of the asteroid fire within the map and integrate into the game  (Aug. 28)
- [x] Update Wiki documentation (Aug. 30)

**Completion Deadline:** Aug. 30

# Member
- Shiyan Su (@ShiyanSu)
