### ISSUE TITLE
Implement the horizontal moving platform obstacle

### ISSUE THREAD

**Issue by ShiyanSu** [UQdeco2800/2021-studio-3#276]
# Description
**Task Name:** Implement the horizontal moving platform obstacle
**Feature:** Obstacle improvement and add more types of obstacles to fit into the new level design
Implement a new type of obstacle that could moving horizontally in a fixed area at a constant speed. The player could jump onto it and must consider the best time to jump on to it.
# Dependencies

- [x] The image of new type platform - should be designed

# Milestones

- [x] Create the `PlatformTask` class. (Oct. 14th)
- [x] Implement `createPlatform3` function to create the moving platform in the `ObstacleFactory` class. (Oct. 14th)
- [x] Update Wiki documentation. (Oct. 15th)

**Completion Deadline:** Oct. 15th

# Member

- Zhiyuan Xu @DLAmeng
