### ISSUE TITLE
Implementation of static obstacle - platform

### ISSUE THREAD

**Issue by ShiyanSu** [UQdeco2800/2021-studio-3#29]
# Description
**Task Name:** Implementation the static obstacle - platform
**Feature:** Obstacle Feature 

The static obstacle platform should appear once the player starts the game and the position of each platform should remain stable within the game. For those platform obstacles on the map, the player could jump onto them and move freely. This obstacle would not cause any damage to the player. Therefore, the player could use them effectively to avoid other types of obstacles

# Dependencies
- [x] Static obstacle - platform should be designed

# Milestones
- [x] Implement createPlatform function to create the platform obstacle in the ObstacleFactory class (Aug. 28)
- [x] Create spawnPlatform function inside the ForestGameArea class (Aug. 28)
- [x] Adjust the position of the platforms within the map and integrate into the game  (Aug. 28)
- [x] Update Wiki documentation (Aug. 30)

**Completion Deadline:** Aug. 30

# Member
- Shiyan Su (@ShiyanSu)
- Zhiyuan Xu (@DLAmeng)
