### ISSUE TITLE
Implement the dynamic obstacle - Robot

### ISSUE THREAD

**Issue by ShiyanSu** [UQdeco2800/2021-studio-3#30]
# Description
**Task Name:** Implement the dynamic obstacle - Robot
**Feature:** Obstacle Feature 

The dynamic obstacle robot should appear once the player starts the game and the position of the robot should be constantly changing. During the game, the robot will move left and right at a constant speed. For the robot on the map, if the player touches them (inside of the attack range of the robot), the player's health will be reduced. The player must try to avoid touching the robot.

# Dependencies
- [x] Dynamic obstacle - should be designed

# Milestones
- [x] Add the configs of robot into obstacle.json (Aug. 29)
- [x] Create the RobotConfig class (Aug. 29)
- [x] Implement createRobot function to create the robot obstacle in the ObstacleFactory class (Aug. 29)
- [x] Create spawnRobot function inside the ForestGameArea class (Aug. 29)
- [x] Adjust the position of the robot within the map and integrate into the game  (Aug. 29)
- [ ] Update Wiki documentation (Aug. 30)

**Completion Deadline:** Aug. 30

# Member
- Shiyan Su (@ShiyanSu)
