### ISSUE TITLE
Implement the dynamic obstacle - UFO obstacle

### ISSUE THREAD

**Issue by DLAmeng** [UQdeco2800/2021-studio-3#31]
# Description
**Task Name** : Implement the dynamic obstacle - UFO
**Feature** : Obstacle Feature

When the game is running, the flying saucer will randomly appear in the upper area of the map and randomly move in different directions. When the player collides with the flying saucer, the player will lose a certain amount of blood.
# Dependencies

- [x] Dynamic obstacle - should be designed
# Milestones

- [x] Implement createUFO function to create the UFO obstacle in the ObstacleFactory class. (Aug. 29)
- [x] Create spawnUFO function inside the ForestGameArea class (Aug. 29)
- [x] Adjust the position of the UFO within the map and integrate into the game (Aug. 29)
- [x] Update Wiki documentation (Aug. 30)

**Completion Deadline: Aug. 30**
# Member

- Zhiyuan Xu(@DLAmeng)

**Comment by ShiyanSu** [comment]
![image](https://user-images.githubusercontent.com/88018792/131303086-1bc009cf-9978-4df8-823e-38e378ebf6a5.png)
