### ISSUE TITLE
Designing the main character 

### ISSUE THREAD

**Issue by sh4453** [UQdeco2800/2021-studio-3#33]
### Description 
Creating the main character that the user will control within the game. Since the theme has been decided as space, the character was subsequently decided to be an astronaut. Also to tie into the apocalyptic theme, a viking edge will also be incorporated into the design. 

### Milestones 
- [x] Establish overall theme and actual astronaut idea - 25/8 
- [x] Draw line art of the astronaut front on and walking to the right- 28/8 
- [x] Color in the line art - 30/8 
- [x] Update wiki documentation - 30/8
