### ISSUE TITLE
Lives Feature

### ISSUE THREAD

**Issue by K0zzas17** [UQdeco2800/2021-studio-3#35]
### **Description** 
The player has a number of lives which describe how many attempts they have to finish the game. Like in most games, once all the lives are exhausted, the player will lose all progress and need to start from the beginning. The player will be able to find more lives as they play through the levels. 

Implementing numerous lives aims to provide an incentive to prolonging gameplay and player engagement. Having more opportunities to respawn after death means the player has more chances to make further progress. Multiple lives also allow beginner players to learn and be comfortable with the game's mechanics before it ends.

### **Dependencies** 
HP bar #19 may need some extra implementation accordingly.

### **Milestones**
- [x] Create Wiki page
- [x] Design new loss screen for when all lives are loss 
- [x] Implement lives functionality
- [x] Update checkpoint feature to incorporate a reset when all lives are lost
