### ISSUE TITLE
Score system

### ISSUE THREAD

**Issue by Gir3245** [UQdeco2800/2021-studio-3#36]
## **Description**
Have a score system that the user will receive at the end of each level that will rely on time, health and potentially collectables that can be on the level. Also show the score on the screen as the player progresses e.g scores decreases as time on level increases and loses health and it increases as the player collects items.

Scoring systems are a key component of game mechanics, and provide a mechanism whereby players are rewarded with point value whenever they accomplish a task in the game this is shown by the players ability to complete the game without getting hit in the shortest time. This gives the player more of an incentive to play the game repetitively which also boosts the player's incentive to challenge themselves and others.

## **Milestones**
Task 1 Generate code for score system #58
Task 2 Design and develop the popup menus to display scores #37

- [x] Finish logic to calculate score  (Sept. 9)
- [x] Display score on game completion (Sept. 12)
- [x] finish wiki page (Sept. 13)

## **Documentation**
[Score System](https://github.com/UQdeco2800/2021-studio-3/wiki/Score-System)
