### ISSUE TITLE
Designing lives and score system assets

### ISSUE THREAD

**Issue by sh4453** [UQdeco2800/2021-studio-3#37]
### Description 
Designing the visual representation of lives on screen, most likely in icon format, for the player to see how many lives they have left. Also adding a score visual to the end screen to show to the player their overall score. 

### Milestones 
- [x] Create lives icons and give to #35 - 4/9
- [x] Modify Team 3's win screen to display score and send to #36 - 4/9 
- [x] Update wiki documentation - 6/9
