### ISSUE TITLE
Buffs & Debuffs

### ISSUE THREAD

**Issue by default-jamc** [UQdeco2800/2021-studio-3#38]
## **Description**
The game requires some mechanism for the player's game-state to change throughout gameplay so that (1) the player is able to handle the obstacles and enemies they are trying to avoid and (2) the game remains interesting and unpredictable for the player. Buffs & Debuffs will be added to the game to allow the player to experience gameplay enhancements and ailments. The implementation will involve designing artefacts which alter the players' state in an interesting but non-gamebreaking way. Buffs/debuffs will spawn as items on the map for the player to collide with to attain. Buffs/debuffs will be removed from the player when they lose a level, or progress to the next. An example of some buffs / debuffs are below. 

| buff | debuff |
|------|-------|
| the player's health is increased by 20 | the players health is decreased by 20 |
| the player does not lose sprint capacity while sprinting for a period of time | the player cannot jump for a period of time |
| the player is invincible for a period of time| all enemies do 200% damage to the player for a period of time |

For the initial implementation of the buffs / debuffs system, the following will be produced:
- **Buff**: the player is invincible for a period of time
- **Buff**: the players' health is increased by a set amount
- **Buff**: the player is able to sprint without losing stamina for a set period
- **Debuff**: the player's health is decreased by a set amount
- **Debuff**: the player is unable to jump for a period of time
- **Debuff**: the player takes double damage for a period of time.

### **Sub-feature / Components**
- Designing of the sprites for the buffs / debuffs
- Implementation of the buffs / debuffs

### **Examples**
- **Buff** When the player collides with a 'buff' item on the map, the bonus pertaining to it will be attributed to them.
- **Debuff** When the player collides with a 'debuff' item on the map, the ailment pertaining to it will be attributed to them.

## **Dependencies**
- [ ] (Extra) Implementation of the Items requires a functioning `Inventory` Component.

## **Milestones**
- [x] Create initial wiki page (Sept. 1)
- [x] Design of 'Buff' Items (@n1ko4fun) #48
    - [x] Design of the Invincibility Buff (Sept. 2)
    - [x] Design of the Health Buff (Sept. 3)
    - [x] Design of the Infinite Stamina Buff (Sept. 6)
- [x] Design of 'Debuff Items' (@WendyW16) #45
    - [x] Design of the Health Debuff (Sept. 4) 
    - [x] Design of the Jump Debuff (Sept. 5)
    - [x] Design of the Double Hurt Debuff (Sept. 7)
        - [x] User Testing for the designs of the artefacts (@WendyW16 , @n1ko4fun)
- [x] Implement the Buff Management System (Sept. 8) (@default-jamc) #39 
    - [x] Write JUnit tests for the buff management system
    - [x] Document code for the new methods & classes
    - [x] Implement the code logic
- [x] Implement the Full Health Restore Buff (Sept. 8) (@default-jamc) #40 
    - [x] Write JUnit tests for the full health restore buff applying
    - [x] Document code for the new methods & classes
    - [x] Implement the code logic
- [x] Implement the Invincibility Buff (Sept. 8) (@default-jamc) #40 
    - [x] Write JUnit tests for the invincibility buff applying
    - [x] Document code for the new methods & classes
    - [x] Implement the code logic
- [x] Implement the Health Buff (Sept. 9) (@Su-LAN) #44 
    - [x] Write JUnit tests for the Health buff applying
    - [x] Document code for the new methods & classes
    - [x] Implement the code logic
- [x] Implement the Health debuff (Sept. 10) (@Su-LAN) #44 
    - [x] Write JUnit tests for the Health debuff applying
    - [x] Document code for the new methods & classes
    - [x] Implement the code logic
- [x] Implement the Jump debuff (Sept. 11) (@raneechu) #41 
    - [x] Write JUnit tests for the Jump debuff applying
    - [x] Document code for the new methods & classes
    - [x] Implement the code logic
- [x] Implement the Double Hurt debuff (Sept. 12) (@default-jamc) #40 
   - [x] Write JUnit tests for the Double Hurt debuff applying
   - [x] Document code for the new methods & classes
   - [x] Implement the code logic
- [x] Implement the Infinite Stamina buff (Sept. 13) (@raneechu) #41 
   - [x] Write JUnit tests for the Stamina buff applying
   - [x] Document code for the new methods & classes
   - [x] Implement the code logic
- [x] Add new changes to game Wiki (Sept. 14)

*Completion Deadline:* Sept. 14

## **Extras**
- [x] Extend the buff system to include items; buffs which are maintained across level changes.

## **Documentation**
- [Wiki page](https://github.com/UQdeco2800/2021-studio-3/wiki/Buffs-&-Debuffs)

## **Members**
- Jazmin (@default-jamc)
- Niko (@n1ko4fun)
- Ranee (@raneechu)
- Su (@Su-LAN)
- Wendy (@WendyW16)

**Comment by sh4453** [comment]
Hey, was wondering if the buff design included modifications to the character? If not, would you guys like me to modify the player asset according to the different buffs you have in mind?

**Comment by default-jamc** [comment]
Hey! The current implementation does support the player being visually modified by the buffs. We are planning on expanding upon this after the functionality is established further. For now, I think we have this aspect organised. However, I noticed that you have been very closely involved with the overall visual design of the game, including the proposed player character design. So we would be happy to discuss design changes and improvements as prototypes are developed for the buffs. :)

**Comment by sh4453** [comment]
Yeah no worries, just let me know on discord what you guys need and I'll be happy to help

**Comment by default-jamc** [comment]
Awesome, will do!

**Comment by BasJW** [comment]
Hey guys, i've recently just made changes to KeyboardPlayerInputComponent by adding a Sprint Modifier variable and a general refactor (#61), so in the future if you ever plan on adding a sprint buff that alters sprint speed it will be alot easier now since that variable is used for controlling sprint. If you're interested, let me know and i can push the changes to main.

**Comment by Su-LAN** [comment]
![241209064_558733948584175_4387087830256154702_n](https://user-images.githubusercontent.com/88018784/132973931-d6f2ac94-6d9c-4bb4-b479-e80bcb1170a7.png)

**Comment by Su-LAN** [comment]
![241755063_714442816178448_9016055948548772494_n](https://user-images.githubusercontent.com/88018784/132974166-aa87307d-29da-4bfc-a87a-bf92534bce87.png)

**Comment by Su-LAN** [comment]
![Buff UML](https://user-images.githubusercontent.com/88018784/133187182-fe937eb3-0aa5-4c2b-9714-5f6aaa3fdbfa.png)
