### ISSUE TITLE
Buff / Debuff Management System

### ISSUE THREAD

**Issue by default-jamc** [UQdeco2800/2021-studio-3#39]
# Description
**Task Name:** Design mechanism for spawning and removing buffs / debuffs.
**Feature:** Buffs / debuffs #38 

As the buffs / debuffs will exist on the map for a period of time (player has a limited time to collect them), we need a system which controls the spawning and despawning of buffs.

This will likely be implemented by some form of `BuffManagement` class which tracks the current buffs which are spawned and collected by the player.

# Milestones
- [x] Update existing `Buffs / Debuffs` Wiki page (Sept. 1)
- [x] Create class for `BuffManagement` (Sept. 3)
- [x] Determine how to control spawning and despawning (Sept. 3)
- [x] Update Wiki documentation (Sept. 4)

**Completion Deadline:** Sept. 5

# Documentation
- [Wiki page](https://github.com/UQdeco2800/2021-studio-3/wiki/Buffs-&-Debuffs)

# Member
- Jazmin (@default-jamc)
