### ISSUE TITLE
Invincibility Buff & Giant Debuff

### ISSUE THREAD

**Issue by default-jamc** [UQdeco2800/2021-studio-3#40]
# Description
**Task Name:** Implement Invincibility buff & 'Giant' debuff.
**Feature:** Buffs / debuffs #38 

The invincibility buff will make the player invincible for a (short) period of time. The 'Giant' debuff will make the player larger, and slightly slower, for a period of time.

Both de/buffs will likely be an `Entity` which has access to the `player` to make changes to its scale and speed. 

# Milestones
- [x] Update existing `Buffs / Debuffs` Wiki page (Sept. 6)
- [x] Implement Invincibility effects on the player (Sept. 7)
- [x] ~~Implement 'Giant' effects on the player (Sept. 8)~~
- [x] Implement the Full Health Restore buff
- [x] Update Wiki documentation (Sept. 9)

**Completion Deadline:** Sept. 10

# Documentation
- [Wiki page](https://github.com/UQdeco2800/2021-studio-3/wiki/Buffs-&-Debuffs)

# Member
- Jazmin (@default-jamc)
