### ISSUE TITLE
Sprint Buff & Jump Debuff

### ISSUE THREAD

**Issue by raneechu** [UQdeco2800/2021-studio-3#41]
# Description
**Task Name:** Implement sprint buff and jump debuff
**Feature:** Buffs/debuffs #38 

The sprinting buff will allow the player to sprint for a period of time without losing stamina. The jump debuff will prevent the player from being able to jump for a period of time.

Both of these will likely be implemented through changing the player state, as well as adjusting the `PlayerActions` and `KeyboardPlayerInputComponent` classes where the jump and sprint functions are implemented.

# Milestones
- [x] Update existing `Buffs/debuffs` Wiki page (Sept 6)
- [x] Implement sprint effects on the player (Sept 7)
- [x] Implement jump effects on the player (Sept 8)
- [x] Update wiki documentation (Sept 9)
- [x] J-unit testing (Sept 11)

# Documentation
- [Wiki page](https://github.com/UQdeco2800/2021-studio-3/wiki/Buffs-&-Debuffs)

# Member
- Ranee (@raneechu)
