### ISSUE TITLE
Implement lives and HUD modification

### ISSUE THREAD

**Issue by K0zzas17** [UQdeco2800/2021-studio-3#42]
## **Description**
Giving the player a set amount of attempts to overcome a level or obstacle is good way of keeping the game interesting while maintaining a certain level of difficulty. Implementation of this feature will give the player a set number of attempts to complete the level from a reached checkpoint; if they fail to do so, they will be punished by having to start the level from the begin once all these lives are exhausted. Future functionality with items may also allow the player to regain lives by picking up a certain item.

**Task**: Player lives: Game life system which determines how many times a player gets to try and finish the game. 
**Feature**: Feature #35 

Player will lose lives upon death. If all lives are exhausted, the player will lose all their items and be forced to start again.

Will require the `PlayerStatsDisplay.java` and `CombatStatsComponent.java` classes to be modified.

### **Milestones**
- [x] Update existing Wiki Page
- [x] Update necessary classes to reflect the implementation
- [x] Design HUD lives assets (if necessary)
- [x] Implement class `LivesComponent.java`
- [x] Implement J-unit tests for any new classes / methods
- [x] Update `ForestGameArea.java`, `PopUpMenuActions.java` and PlayerStatsDisplay.java`
- [x] Update wiki page
