### ISSUE TITLE
Design Custom Loss Screens

### ISSUE THREAD

**Issue by yeegoh** [UQdeco2800/2021-studio-3#43]
# Description
As there are various loss conditions, custom death screens will be designed to display and notify the player of the reason for death. Some information about the enemy obstacle will also be presented to the player, along with their score and button options to redirect to the main menu screen or replay from a checkpoint. So far, the obstacles which cause death are flying rocks, a robot, a ufo and fiery asteroids. The screens will have a blank area to insert text within the game,  which will include the score and possibly player stats (eg. times jumped, number of power-ups used, number of lives collected, etc.)

**Design Reference:** A game inspiration comes from [Cuphead's custom death screens](https://www.youtube.com/watch?v=qN7C_8G5kRk), where the boss and a quote is displayed when the player dies: 
<img src="https://user-images.githubusercontent.com/70673799/131955838-a137af45-074f-4c75-8f1e-fd278d0b5f0d.png" width="500">

# Milestones
- [x] Design new win screen (07/09)
- [x] Design custom death screens according to the obstacle which caused death (08/09)
- [x] Update wiki documentation (10/09)

## Documentation
[Design Guide](https://github.com/UQdeco2800/2021-studio-3/wiki/Design-Guide)
[Score System](https://github.com/UQdeco2800/2021-studio-3/wiki/Score-System)

## Members
- Yee Ping Goh (@yeegoh) (Yee Goh)

**Comment by yeegoh** [comment]
Feedback welcomed :)

<img width="400" alt="example interface" src="https://user-images.githubusercontent.com/70673799/132663529-d1b5198a-407b-4b6c-af28-59ea293da590.png">
<img width="400" alt="robotDeath" src="https://user-images.githubusercontent.com/70673799/132663536-e7f41dc1-1ba4-4e31-8751-70d8220b97a2.png">
<img width="400" alt="ufoDeath" src="https://user-images.githubusercontent.com/70673799/132663537-7b5846aa-a5d4-4a37-9484-de36e0491259.png">
<img width="400" alt="asteroidDeath" src="https://user-images.githubusercontent.com/70673799/132663545-1394e696-ecff-4a55-9c3a-d5c636f53236.png">
<img width="400" alt="winScreen" src="https://user-images.githubusercontent.com/70673799/132664317-f1bc7af9-b7fe-4e60-866e-053c56972cb7.png">

<img width="150" alt="" src="https://user-images.githubusercontent.com/70673799/132664408-839aed14-a24d-4a8d-bc0e-cfb9aac39620.png">
<img width="150" alt="" src="https://user-images.githubusercontent.com/70673799/132664413-9e9157aa-ae32-4144-a002-181e2a6f5352.png">
<img width="150" alt="" src="https://user-images.githubusercontent.com/70673799/132664416-261e6c2e-9f7d-40d0-8856-c04583e3e2ca.png">
