### ISSUE TITLE
The Health Buff &Debuff

### ISSUE THREAD

**Issue by Su-LAN** [UQdeco2800/2021-studio-3#44]
## **Description**
**Task Name:** Implement health buff and health debuff
**Feature:** Buffs/debuffs #38 
| buff | debuff |
|------|-------|
| the player's health is increased by 20 | the player's health is decreased by 20 |

The max health can be increased by collecting the Health Bar, and the health will decrease by collecting the debuff
## **Milestones**
- [x] Create wiki page (Sept. 3)
- [x] Done health buff  (Sept. 7)
- [x] Done health debuff (Sept. 8)
- [x] finish wiki page (Sept. 13)
- *Completion Deadline:* Sept. 14
## **Documentation**
- [Wiki page](https://github.com/UQdeco2800/2021-studio-3/wiki/Buffs-&-Debuffs)
