### ISSUE TITLE
Design “Debuff” items

### ISSUE THREAD

**Issue by WendyW16** [UQdeco2800/2021-studio-3#45]
# **Description**
**Task Name**: Design the Debuff items obtained by players colliding in the game.
**Feature**: Buffs & Debuffs #38

According to the different debuff functions acquired by the player, different types of appearances and page expressions are designed.

- the player's health is decreased by a set amount
- the player is unable to jump for a period of time
- the player takes double damage for a period of time
 
# **Milestones**
- [x] Design three debuff sketches (Sep 7)
- [x] Design the appearance of three debuffs (Sep 10)
- [x] Design three debuff page presentation methods (Sep 10)
- [x] Update wiki documentation(Sep 13)
 
**Completion Deadline:** Sep  14
 
 
# **Documentation**
- [Wiki link](https://github.com/UQdeco2800/2021-studio-3/wiki/Buffs-&-Debuffs)

 
# **Member**
- Wendy (@WendyW16 )

**Comment by WendyW16** [comment]
<img width="699" alt="屏幕快照 2021-09-12 下午2 41 03" src="https://user-images.githubusercontent.com/88033083/132972560-05c32d7e-359d-481f-be98-f4029c2dbc89.png">

**Comment by WendyW16** [comment]
<img width="349" alt="屏幕快照 2021-09-12 下午2 48 34" src="https://user-images.githubusercontent.com/88033083/132972621-90d76eeb-e8ba-49d9-b748-de662acbd696.png">
<img width="355" alt="屏幕快照 2021-09-12 下午2 48 47" src="https://user-images.githubusercontent.com/88033083/132972624-e2b42743-862f-4ce7-86d7-2fa2313092fb.png">
<img width="377" alt="屏幕快照 2021-09-12 下午2 49 00" src="https://user-images.githubusercontent.com/88033083/132972625-c5d1447a-5415-4f06-9e94-1975ccc06b91.png">

**Comment by WendyW16** [comment]
<img width="344" alt="WechatIMG157" src="https://user-images.githubusercontent.com/88033083/133046228-bb974409-d8fc-4bf4-bfad-67603058e1f6.png">
<img width="348" alt="WechatIMG158" src="https://user-images.githubusercontent.com/88033083/133046503-a2068e6b-730a-4dfb-9167-2fb4584055fc.png">
<img width="343" alt="WechatIMG159" src="https://user-images.githubusercontent.com/88033083/133046603-fcebd488-0313-4a6c-b987-e04f3b8683a7.png">
