### ISSUE TITLE
Updated Movement Controller for Animations

### ISSUE THREAD

**Issue by SirAardvark** [UQdeco2800/2021-studio-3#46]
# Description
The core movement code has been added in sprint one however a controller needs to be made to control which state the player is currently in. The player should only be in one state at a time.

Currently the player can be in multiple movement states. e.g. The player can be in a sprinting and jumping state. With the current code it is difficult to add player animations as you can be in multiple movement states.

# Milestones

**Goal 1 - State Management** (Ticket #51) (@BasJW)
- [x] Create State Management Controller Class
- [x] Implement state selection logic
- [x] Test logic on all possible player states
- [x] Compare player states with animation
- [x] Write Junit tests
- [x] Update wiki page

**Goal 2 - Create Animations** (Ticket #53) (@paulchoi610, @ShahM1h1r)
- [x] Create all player state animations 
- [x] Convert all animations to correct file type for LibGDX

**Goal 3 -  Implement Animations** (Ticket #59) (@SirAardvark)
- [x] Implement the animations within the game 
- [x] Test that all possible states work correctly
- [x] Update wiki documentation

**Goal 4 -  Refactor KeyboardPlayerInputComponent & Sprint Functionality** (Ticket #61) (@BasJW)
- [x] Refactor KeyboardPlayerInputComponent
- [x] Allow Sprint to use a Sprint Modifier
- [x] Update wiki documentation

# Documentation

[KeyboardPlayerInputComponent & Player Sprint Refactor](https://github.com/UQdeco2800/2021-studio-3/wiki/KeyboardPlayerInputComponent-&-Player-Sprint-Refactor.)

[Player State Manager](https://github.com/UQdeco2800/2021-studio-3/wiki/Player-State-Manager)

...
Members
Sebastian (@BasJW)
Paul (@paulchoi610)
Mihir (@ShahM1h1r )
Justin (@SirAardvark ) (Justin Aavik)
Kevin(@Dollar0712 ) (Kaipeng Zhang)

**Comment by SirAardvark** [comment]
Added task ticket numbers, name and split up goal 2 and 3 for making vs implementing the animations.
