### ISSUE TITLE
Camera Moving

### ISSUE THREAD

**Issue by SirAardvark** [UQdeco2800/2021-studio-3#47]
### Description
The camera will follow the player through a long map and stop tracking when the player is near the border of the map.

### Milestones
Goal 1 - Camera track the player #56
- [x] Implement code logic
- [x] Write Junit tests
- [x] Create Documentation

Goal 2- Camera stop Tracking #69
- [x] Implement code logic
- [x] Write Junit tests
- [x] Create Documentation

### Documentation
[Camera tracking player](https://github.com/UQdeco2800/2021-studio-3/wiki/Camera-tracking-player)

...
Members
Sebastian (@BasJW)
Paul (@paulchoi610)
Mihir (@ShahM1h1r )
Justin (@SirAardvark ) (Justin Aavik)
Kevin(@Dollar0712 ) (Kaipeng Zhang)

**Comment by Dollar0712** [comment]
@jackemerson

**Comment by jackemerson** [comment]
Similar to what I said in my reply to #56 , the linked task looks more like the feature ticket than perhaps this one does.

Perhaps these two are separate:
> Make the camera track the player
> Make the camera track or stop once the player reaches or arrives at the specified location.
Though you'll have a better idea than me, as you're working on the feature.


Likely you've also explored different methods of camera tracking. In future, you might consider that research as a task in itself.
