### ISSUE TITLE
Design of Buff features

### ISSUE THREAD

**Issue by n1ko4fun** [UQdeco2800/2021-studio-3#48]
### Description
**Task Name**: Designing Buff visual effects in the game.
**Feature**: Buffs&Debuffs #38

The feature is aimed to design Buff visual effects while players is getting benefits by particular operations where the functionalities include three different elements.

1. design the animation where the player's health is increased by 20
2. design the animation where  the player will sprint for a period of time without losing stamina
3. design the animation that make the player invincible for a period of time.

### Milestones
- [x] draft each single function sketches.(Sep 7)
- [x] Implement user test about draft.(Sep 8)
- [x] Create the appearance of Buff features combined by interviewees suggestions.(Sep 10)
- [x] Design the Buff page presentation methods. (Sep 11)
- [x] Update wiki documentation(Sep 13)

**Complete Deadline：** Sep 14

### Documentation
[@]Wiki page(https://github.com/UQdeco2800/2021-studio-3/wiki/Buff-Catalogue)

### Member

- Niko (@n1ko4fun )

**Comment by Su-LAN** [comment]
![241634081_836809347008098_27569694135278685_n](https://user-images.githubusercontent.com/88018784/132946853-7b7932be-5b90-4989-ad60-c2aad0379b3c.jpg)
![241644960_858740131447222_5880597129258556069_n](https://user-images.githubusercontent.com/88018784/132946854-10780164-a901-4160-855f-c9405428aa46.jpg)
![241687252_964880280910604_7333647453519678091_n](https://user-images.githubusercontent.com/88018784/132946856-6e083164-d9ff-40b0-8b28-ee9f1538699c.jpg)
![241644960_858740131447222_5880597129258556069_n (1)](https://user-images.githubusercontent.com/88018784/132946857-fe8572b3-ee21-4025-a902-acdb2bf57d3f.jpg)

**Comment by n1ko4fun** [comment]
[](url)
![cant jump](https://user-images.githubusercontent.com/88018782/133041298-d97ef7ce-87e6-44d0-aa27-f51aca69f3bc.png)
![sprint](https://user-images.githubusercontent.com/88018782/133041314-d88ad950-7141-4abf-8719-2cdec6ec5948.png)
![increase blood](https://user-images.githubusercontent.com/88018782/133041327-6e193d0c-8242-416d-8fe9-4b1099b962e9.png)
![IMG_1247](https://user-images.githubusercontent.com/88018782/133041517-9141b38d-e9f7-43c5-a11e-e8611c55f044.JPG)

**Comment by n1ko4fun** [comment]
![4](https://user-images.githubusercontent.com/88018782/133045330-b219a7c7-d47c-4408-a453-83d794b150df.PNG)
![DA952E13-9F5E-493D-B7E2-7CC73C97AA1C](https://user-images.githubusercontent.com/88018782/133045351-eaa197cc-2a98-4d2a-8a05-ee33afd7d01a.PNG)

**Comment by n1ko4fun** [comment]
![IMG_1247](https://user-images.githubusercontent.com/88018782/133045521-0a1f8d7f-c097-45d4-898f-07d6f3d7c7c0.JPG)

**Comment by n1ko4fun** [comment]
![cant jump](https://user-images.githubusercontent.com/88018782/133178490-736241d2-4b16-446c-a400-8ad3c0c77f7a.png)
![sprint](https://user-images.githubusercontent.com/88018782/133178492-1b458d94-770a-4159-948d-71850c0413b5.png)
![increase blood](https://user-images.githubusercontent.com/88018782/133178493-0ae13332-d396-493d-bc83-8ca54a88cda0.png)

**Comment by n1ko4fun** [comment]
![cant jump](https://user-images.githubusercontent.com/88018782/133178753-b4f3a1cf-c641-480d-a4de-11eeaf1cf0be.png)

**Comment by n1ko4fun** [comment]
![cant jump](https://user-images.githubusercontent.com/88018782/133178783-ab31244b-6f4f-4330-83e4-6bfb7d482adf.png)

**Comment by n1ko4fun** [comment]
![sprint](https://user-images.githubusercontent.com/88018782/133178865-897605d7-e049-4ff0-8cfa-b0076f91eba1.png)
![increase blood](https://user-images.githubusercontent.com/88018782/133178868-f137cb9f-4b9e-4e98-93b4-fbdc52dd2b42.png)

**Comment by n1ko4fun** [comment]
![cant jump](https://user-images.githubusercontent.com/88018782/133178994-dabb1788-080c-4d06-9916-6cbe213775ef.png)

**Comment by n1ko4fun** [comment]
![画板 1sprint](https://user-images.githubusercontent.com/88018782/137666687-9369ab05-af18-40d0-a1dc-02987d21cd33.png)
![画板 1cant jump](https://user-images.githubusercontent.com/88018782/137666693-cc02b67f-c6ff-4b3a-a5e1-4f5329d4cfa6.png)
<img width="387" alt="Screen Shot 2021-10-18 at 13 51 08" src="https://user-images.githubusercontent.com/88018782/137666719-243e8e57-a2e0-444e-b44b-d9519aca01d5.png">
