### ISSUE TITLE
Obstacles/enemies animation effect

### ISSUE THREAD

**Issue by emily-dl** [UQdeco2800/2021-studio-3#49]
# Description

For this obstacle/enemies animation effect feature, our team is going to create and implement animation effects for different obstacles/enemies. The animation effects will make the obstacle more visually realistic and also make the game more interactive.

## Examples

UFO: the UFO hovering in the sky when the player approaches the UFO's detecter light will change to yellow and generates the harmful wave. Then it starts chasing the player, which causes 20 per cent of health bar damage each time
# Dependencies

- [x] Implementation of obstacle feature
- [x] Design the animation effects of obstacles

### Milestones

- [x] Update Obstacles Wiki page 
- [x] Design animation effects for UFO, robots & asteroid fire (7th Sept) #54 @emily-dl 
- [x] Design one or more new obstacle/enemies with animations (10th Sept) 
- [x] Implement the animation effects for UFO (11th Sept) #70 @DLAmeng 
- [x] Implement the animation effects for robots (11th Sept) #57 @ShiyanSu 
- [x] Implement the animation effects for asteroid fire (11th Sept) #68 @ShiyanSu 
- [x] Write the wiki page (11th Sept)

# **Documentation**
- [Obstacle wiki](https://github.com/UQdeco2800/2021-studio-3/wiki/Obstacles)
- [UFO_animation wiki](https://github.com/UQdeco2800/2021-studio-3/wiki/UFO_animation-Function)
- [Asteroid fire animation functionalities](https://github.com/UQdeco2800/2021-studio-3/wiki/Asteroid-fire-animation-functionalities)
- [Robot animation functionalities](https://github.com/UQdeco2800/2021-studio-3/wiki/Robot-animation-functionalities)
- [Obstacle Animation User Testing](https://github.com/UQdeco2800/2021-studio-3/wiki/Obstacle-Animation-User-Testing)

# Members

- Emily Zeng (@emily-dl) (Emily Zeng)
- Shiyan Su (@ShiyanSu) (Shiyan Su)
- Zhiyuan Xu (@DLAmeng)
- Thomas Mann (@44806158)
