### ISSUE TITLE
Player State Management

### ISSUE THREAD

**Issue by BasJW** [UQdeco2800/2021-studio-3#51]
# Description

**Task:** Player State Management
**Feature:** Updated Movement Controller for Animations #46

This task regards implementing a manager for the current play state. Since the player can now sprint and jump whilst being at different health intervals, there are many different 'states' a player can be in. As such, a new `PlayerStateComponent` class will be made for this purpose. This new class will help manage what animation should be triggered based upon what actions the player is performing.

# Milestones

- [x] Create wiki page - Sep 8
- [x] Make the new component class - Sep 9
- [x] Determine enum names and values for states - Sep 10
- [x] Implement logic for determining which state the player is in - Sep 11 
- [x] Write Junit Tests for class - Sep 13
- [x] Finish wiki page - Sep 14

**Completion Deadline:** Sep 14

# Documentation
[Relevant wiki page](https://github.com/UQdeco2800/2021-studio-3/wiki/Player-State-Manager)

# Member
Sebastian (BasJW)
