### ISSUE TITLE
Implementing the Custom loss screens 

### ISSUE THREAD

**Issue by sh4453** [UQdeco2800/2021-studio-3#52]
### Description 
Implementing the Custom lose screens into the game created by #43, after a player has died due to a certain enemy.

### Milestones
- [ ] Complete lose screens - 8/9
- [ ] Inspect code - 10/9 
- [ ] Create classes for the custom screens - 11/9
- [ ] Create Events to trigger the customer screens - 12/9 
- [ ] Update Wiki Documentation - 13/9
