### ISSUE TITLE
State Player Animation

### ISSUE THREAD

**Issue by ShahM1h1r** [UQdeco2800/2021-studio-3#53]
**Task: Player Animation
Feature: Additional Player Movement & Animation**

We will be creating the damage states for the Jump, Walk, and Sprint movement states. As the player can alternate between these movement states whilst simultaneously being in different damage states, animations for the different damage states must be made for each movement state. The damage animations will contain four different states in health intervals of 91%-100% (base model), 51%-90%, 11%-50% and 1%-10% (dead model as currently damage intervals are 10 damage).

**Example**
When the character health drops to 80% the character will have the damage state of the 51%-90% health interval.

**Milestones**
List of steps that need to be completed for this task.

- [x] Damage Jump Frame Animations ()
- [x] Damage Sprint Frame Animations ()
- [x] Damage Walk Frame Animations ()

Documentation
[Character Design Guide](https://github.com/UQdeco2800/2021-studio-3/wiki/Character-Design-and-Animations)

Member
Mihir (@ShahM1h1r )
Paul (@paulchoi610 )

**Comment by SirAardvark** [comment]
When creating the .atlas files make sure there is a default parameter as without it the animation does not work in libGDX. 
I have added it to all current .atlas files. 

![image](https://user-images.githubusercontent.com/69832032/132937485-9ee26bae-6139-40fc-8944-a67733736e1f.png)

**Comment by paulchoi610** [comment]
Just pushed updated files combining all the images into one sprite sheet. Also included the default parameters.

**Comment by paulchoi610** [comment]
@ShahM1h1r Created a wiki page for damage animations https://github.com/UQdeco2800/2021-studio-3/wiki/Character-Damage-Animations
