### ISSUE TITLE
Design obstacles/enemies animation

### ISSUE THREAD

**Issue by emily-dl** [UQdeco2800/2021-studio-3#54]
### Task description
This task is to design three animations for the asteroid, robot and the UFO

The asteroid animation: asteroid fire

The robot animation: As the robot comes from the right to left, it switches the peace mode to "attack" mode. The "attack mode" robot has aggressive red-eye and it raises its arm and shoots stones to the left side.

The UFO: change from "no harmful wave" status to "harmful wave" status. The harmful wave will cause the player additional health damage when the player is exposed to the harmful wave.

### Milestones
- [x] Draft animation: 6th Sept
- [x] User testing: 7th Sept
- [x] Final version finish by: 8th Sept
