### ISSUE TITLE
Camera tracking player

### ISSUE THREAD

**Issue by Dollar0712** [UQdeco2800/2021-studio-3#56]
## Task description
**Task:** Camera tracking player
**Feature:** Camera Moving #47

This task is designed to add camera tracking to long horizontal maps, and depending on the player's position to determine where the camera should be to prevent the player's interface from appearing off-map.
## Milestones
- [x] Make the camera track the player - Sep 8
- [x] Test the logic of the camera moving - Sep 10
- [x] Write Junit tests - Sep 11
- [x] Update wiki page - Sep 12

Completion Deadline: Sep 14
## Documentation
[Camera tracking player](https://github.com/UQdeco2800/2021-studio-3/wiki/Camera-tracking-player)

Member
Kevin (@Dollar0712)

**Comment by jackemerson** [comment]
This is more a feature ticket than a task, in some ways.
