### ISSUE TITLE
Implement the animation effect for Robot

### ISSUE THREAD

**Issue by ShiyanSu** [UQdeco2800/2021-studio-3#57]
# Description
**Task Name:** Implement the animation effect for Robot
**Feature:** Obstacle/enemies animation feature 

The animation effect for the robot should be: 
1. At the beginning of the game, the robot should be in a normal mode and the eyes do not turn red.
2. As time passed, the robot will turn into attack mode which its eyes will become red and it will stretch out its arm to extend its range of attack.

# Dependencies
- [x] Animation effects and images of robot - should be designed

# Milestones
- [x] Write the robot.atlas to create the animation (Sept. 07)
- [x] Add the animation to createRobot function in the ObstacleFactory class (Sept. 08)
- [x] Update Wiki documentation (Sept. 08) [wiki](https://github.com/UQdeco2800/2021-studio-3/wiki/Robot-animation-functionalities)

**Completion Deadline:** Sept. 08

# Member
- Shiyan Su (@ShiyanSu)

**Comment by ShiyanSu** [comment]
![robot_animation (2)](https://user-images.githubusercontent.com/88018792/133200694-555c78bd-9367-409f-b808-03a304433ac5.png)
