### ISSUE TITLE
Score tracking and display

### ISSUE THREAD

**Issue by Gir3245** [UQdeco2800/2021-studio-3#58]
## **Description**
Implement the logic to track the user's score throughout the game. The score should be based of time, health, and leave flexibility to add other modifiers in the future. The score should then be displayed on the popup screens for the user to see and if not too much HUD area is taken, a live score should be displayed.

### **Dependencies**
The design assets from #37

## **Milestones**
- [x] Determine how the score will be calculated (Sept. 7)
- [x] Finish logic to calculate score  (Sept. 9)
- [x] Display score on game completion and lose (Sept. 12)
- [x] Implement the new win screen and lose screen (sept. 13)
- [x] finish wiki page (Sept. 13)

## **Documentation**
[Score System](https://github.com/UQdeco2800/2021-studio-3/wiki/Score-System)
