### ISSUE TITLE
Implement Player State Animations

### ISSUE THREAD

**Issue by SirAardvark** [UQdeco2800/2021-studio-3#59]
### Description
Once the player state management has been implemented, the player will need to have a visual indicator to know which state they are in such as running, walking, sprinting etc.

### Dependency's
Player State Management #51 
- The code will need to be able to say which state to be in before I can implement them
- The player animations can be tested by manually calling them in `KeyboardPlayerInput` if the animations are ready before the player state manager

State Player Animation #53 
- The animations need to be made before I can implement them

### Milestones

- [x] Test animations manually
- [x] Implement logic to change players animation
- [x] Implement logic into the Player State Manager
- [x] Write Junit tests
- [x] Add to the player state wiki (Maybe create own wiki for animations) 

Completion Deadline - Sept 14

### Members
Justin (@SirAardvark )
