### ISSUE TITLE
Design background 

### ISSUE THREAD

**Issue by emily-dl** [UQdeco2800/2021-studio-3#60]
### Task description
This task is to design three-game background elements

element one: space-themed base background
element two: ground platform background
element three: ground surface background

### Milestones
- [x] Draft finish by: 10th Sept
- [x] User testing: 11 th Sept
- [x] Final version finish by: 12th Sept
