### ISSUE TITLE
Refactor KeyboardPlayerInputComponent

### ISSUE THREAD

**Issue by BasJW** [UQdeco2800/2021-studio-3#61]
# Description

**Task:** Refactor KeyboardPlayerInputComponent
**Feature:** Updated Movement Controller for Animations #46

The current KeyboardPlayerInputComponent class works as intended, however the code can be difficult to read at times, and repeated code is quite prevalent. Hence, a refactor of the class will be done, factoring out similar functionality into methods. Additionally, I plan on adding a `SPRINT_MODIFIER` variable so that in future, the sprint functionality can be modified easily.

Another advantage of refactoring the KeyboardPlayerInputComponent class is that it will be a lot easier to implement the player state system, as seen in #51

# Milestones

- [x] Create Wiki page - Sep 10
- [x] Refactor `KeyboardPlayerInputComponent` - Sep 10
- [x] Refactor `Sprint` to use a `SPRINT_MODIFIER` - Sep 11
- [x] Finish Wiki page - Sep 12

# Documentation

[Relevant wiki page](https://github.com/UQdeco2800/2021-studio-3/wiki/KeyboardPlayerInputComponent-&-Player-Sprint-Refactor.)

# Member
Sebastian (BasJW)
