### ISSUE TITLE
Implement Full Health Restore (buff) and Double Hurt (debuff)

### ISSUE THREAD

**Issue by default-jamc** [UQdeco2800/2021-studio-3#62]
# Description
**Task Name:** Implement Full Health Restore buff and Double Hurt debuff.
**Feature:** Buffs / debuffs #38 

The full health restore buff will restore the players' health to full upon collision. The double hurt debuff will cause all damage dealt to the player to be doubled for a period of time.

Implementation of these buffs will make changes to the `BuffManager`, `BuffInformation`, `CombatStatsComponent` and `PlayerBuffs` classes.

# Milestones
- [x] Update existing `Buffs / Debuffs` Wiki page (Sept. 9)
- [x] Implement Full Health Restore effects on the player (Sept. 10)
- [x] Implement Double Hurt effects on the player (Sept. 10)
- [x] Update Wiki documentation (Sept. 10)

**Completion Deadline:** Sept. 10

## Dependencies
- Designs for the buffs / debuffs will need to be completed before integration into the final game (#48 #45)

# Documentation
- [Buff / Debuff wiki page](https://github.com/UQdeco2800/2021-studio-3/wiki/Buffs-&-Debuffs)
- [Buff Catalogue](https://github.com/UQdeco2800/2021-studio-3/wiki/Buff-Catalogue)
- [Debuff Catalogue](https://github.com/UQdeco2800/2021-studio-3/wiki/Debuff-Catalogue)

# Member
- Jazmin (@default-jamc)
