### ISSUE TITLE
New game background

### ISSUE THREAD

**Issue by emily-dl** [UQdeco2800/2021-studio-3#63]
# Description

Our team is going to implement the space theme background and platform background that consists of smaller units images to suit the game story. For each game level, the background will be different.

# Dependencies

- [x] Background design

### Milestones

- [x] Design the first background image elements (space, earth ground etc.) (10th Sept) #60 @emily-dl 
- [x] User Testing of background image elements and animation (12 Sept) 
- [x] Implement the background to the first game level. (13 Sept) #72 @ShiyanSu 
- [x] Update wiki (13 Sept) [Game background wiki](https://github.com/UQdeco2800/2021-studio-3/wiki/Game-Background)

# **Documentation**
- [Wiki page](https://github.com/UQdeco2800/2021-studio-3/wiki/Obstacles)
- [Game background wiki](https://github.com/UQdeco2800/2021-studio-3/wiki/Game-Background)

# Members

- Emily Zeng (@emily-dl) (Emily Zeng)
- Shiyan Su (@ShiyanSu) (Shiyan Su)
- Zhiyuan Xu (@DLAmeng)
- Thomas Mann (@44806158)
