### ISSUE TITLE
Instant Buff Animations

### ISSUE THREAD

**Issue by raneechu** [UQdeco2800/2021-studio-3#64]
# Description
**Task Name:** Implement instant buff animations
**Feature:** Buffs/Debuffs #38 

Once a player collects a HP up or HP down buff, an instant animation will float from the player indicating gain/loss of health.
In order to get the animation to float, an entity with a movement task will need to be created. The `ForestGameArea` class will hold the spawn function for the animation and the `BuffManager` class will likely call the spawning function on collision with a buff.

Note: This addition was decided close to the end of the sprint, so may not be perfect

# Milestones
- [x] Update existing `Buffs/debuffs` Wiki page (Sept 12)
- [x] Implement factory class for the entity (Sept 12)
- [x] Implement spawn functionality (Sept 12)
- [x] Update wiki documentation (Sept 13)
- [x] J-unit testing (Sept 13)

# Documentation
- [Wiki Page](https://github.com/UQdeco2800/2021-studio-3/wiki/Instant-Buff-Pickup-Animation)

# Member
- Ranee (@raneechu)
