### ISSUE TITLE
Implement buff and debuff images to appear above the character

### ISSUE THREAD

**Issue by Su-LAN** [UQdeco2800/2021-studio-3#65]
## **Description**
**Task Name:** Implement buff and debuff images to appear above the character
**Feature:** Buffs/debuffs #38 

When characters pick up buffs and debuffs, the buff and debuff will appear above the player's blood bar, and when the effect disappears, the image will follow

## **Milestones**
- [x] Create wiki page (Sept. 3)
- [x] Done health buff  (Sept. 7)
- [x] finish wiki page (Sept. 13)

## **Documentation**
- [Wiki page](https://github.com/UQdeco2800/2021-studio-3/wiki/Buffs-&-Debuffs)
