### ISSUE TITLE
Implement the animation effect for Asteroid fire

### ISSUE THREAD

**Issue by ShiyanSu** [UQdeco2800/2021-studio-3#68]
# Description
**Task Name:** Implement the animation effect for Asteroid fire
**Feature:** Obstacle/enemies animation feature 

The animation effect for the asteroid fire should look like the simulation of the real fire.

# Dependencies
- [x] Animation effects and images of asteroid fire- should be designed

# Milestones
- [x] Write the asteroidFire.atlas to create the animation (Sept. 09)
- [x] Add the animation to createAsteroidFire function in the ObstacleFactory class (Sept. 09)
- [x] Update Wiki documentation (Sept. 10) [wiki](https://github.com/UQdeco2800/2021-studio-3/wiki/Asteroid-fire-animation-functionalities)

**Completion Deadline:** Sept. 10

# Member
- Shiyan Su (@ShiyanSu)

**Comment by ShiyanSu** [comment]
![asteriod (1)](https://user-images.githubusercontent.com/88018792/133200885-68bab185-b24a-44c8-b6a6-1c60dc4112ab.png)
