### ISSUE TITLE
Camera stop Tracking

### ISSUE THREAD

**Issue by Dollar0712** [UQdeco2800/2021-studio-3#69]
## Task description
**Task:** Camera stop Tracking
**Feature:** Camera Moving #47

This task is designed to add camera tracking to long horizontal maps, and depending on the player's position to determine where the camera should be to prevent the player's interface from appearing off-map.
## Milestones
- [x] Make the camera track or stop once the player reaches or arrives at the specified location. - Sep 10
- [x] Test the logic of the camera stoping - Sep 10
- [x] Write Junit tests - Sep 11
- [x] Update wiki page - Sep 12

Completion Deadline: Sep 14
## Documentation
[Camera tracking player](https://github.com/UQdeco2800/2021-studio-3/wiki/Camera-tracking-player)

Member
Kevin (@Dollar0712)
