### ISSUE TITLE
Obstacle Feature

### ISSUE THREAD

**Issue by ShiyanSu** [UQdeco2800/2021-studio-3#7]
### Description

To make the game become more challenging and immerse the player into the atmosphere of the game, we aim to implement the obstacle feature for the game. As the game character progresses from left to right, obstacles will appear either from the game character’s right hand side or from the sky. However, when it comes to the higher level of the game, obstacles will also appear at the left hand side of the game character when the player moves backward to avoid obstacles ahead. In addition, different types of obstacles will cause different amounts of damage to the game character. In order to survive the game, the player must try to avoid as many obstacles as possible. The team will design and implement the obstacle feature for the game.

#### SubFeature

1. Static obstacles that require players to jump/slide down to avoid.
2. Dynamic free-moving obstacles that require players to combine multiple movements such as jumping (jump to a safe platform or over)/sliding down/waiting until it passes.

### Examples

- Asteroid: A dynamic obstacle appears from the sky, hits the land and causes a crater. As the game character approaches the crater, the character should jump over it.
- Volcano eruption: The player must jump to a safe platform to avoid the lava.

### Dependencies

- [x] Player movement feature.
- [x] Game maps for each level.

### Milestones

- [x] Design the feature of all obstacles add documentation to Wiki (Aug.18)
    - [x] Graphic design of each type of obstacle.
    - [x] Functionality of each type of obstacle, including its appearance and how it interacts with the character.
    - [x] Design varying functionality for the different game levels.
    - [x] Update wiki.
- [x] Create Obstacle abstract class to represent all types of the obstacle. (Aug.23)
    - [x] Write JavaDoc for Obstacle.
    - [x] Create JUnit tests for Obstacle.
    - [x] Implement the logic for Obstacle.
- [x] Create classes for each type of obstacle. (Aug.25)
    - [x] Write JavaDoc.
    - [x] Create JUnit tests.
    - [x] Implement the logic.
- [x] Debug and fix issues. (Aug.28)
- [x] Integrate into the game. (Aug.30)

## **Documentation**
- [Wiki page](https://github.com/UQdeco2800/2021-studio-3/wiki/Obstacles)

### Members

- Emily Zeng (@emily-dl) (Emily Zeng)
- Yee Ping Goh (@yeegoh) (Yee Goh)
- Shiyan Su (@ShiyanSu) (Shiyan Su)
- Zhiyuan Xu (@DLAmeng)
- Thomas Mann (@44806158)

**Comment by jackemerson** [comment]
This feature should be fine. Generate and assign task tickets; I'll approve this feature, once that's done.
