### ISSUE TITLE
Implement the animation effect for UFO

### ISSUE THREAD

**Issue by DLAmeng** [UQdeco2800/2021-studio-3#70]
### Description
**Task Name:** Implement the animation effect for UFO
**Feature:** UFO animation feature

When the player approaches the UFO, the ufo will emit light.
### Dependencies
- [ ] Animation effects and images of ufo-animation should be designed
### Miletones
- [ ] Write the ufo-animation.atlas to create the animation(Sept. 09)
- [ ] Add the animation of createUFO function in the ObstacieFactory class(Sept. 09)
- [ ] Update Wiki documentation(Sept. 10)

Completion Deadline: Sept. 10
### Member
- Zhiyuan Xu(@DLAmeng )

**Comment by ShiyanSu** [comment]
![ufo_animation-01](https://user-images.githubusercontent.com/88018792/133200478-9a7f2e25-0d7d-4a79-8c4c-239fc29d70c3.png)
