### ISSUE TITLE
Implement the new game background

### ISSUE THREAD

**Issue by ShiyanSu** [UQdeco2800/2021-studio-3#72]
# Description
**Task Name:** Implement the new game background
**Feature:** New game background

Implement the new game background to echo the story line of the game.

# Dependencies
- [x] New game background - should be designed

# Milestones
- [x] Add the textures of new game background (Sept. 12)
- [x] Draw the new game background in TerrainFactory class (Sept. 12)
- [x] Update Wiki documentation (Sept. 13)

**Completion Deadline:** Sept. 13

# Member
- Shiyan Su (@ShiyanSu)

**Comment by ShiyanSu** [comment]
![Class diagram with UML notation](https://user-images.githubusercontent.com/88018792/133191581-14c96471-c507-41db-9e8b-dfe0c2fee393.png)
