### ISSUE TITLE
Implementing a new level terrain

### ISSUE THREAD

**Issue by Gir3245** [UQdeco2800/2021-studio-3#80]
# Description

Design new level terrains by altering the current floor implementation. Altering the level terrain will allow for variations in the game's terrain, allowing implementations for pitfalls, hills, valleys etc.

The current map terrain is to be updated to be more dynamic; as of right now, the current map terrain design is simple, designed simply to allow tests on player movement to be conducted in game. In order to improve this a new terrain will be designed, complete with elements that will increase in challenge as the player progresses. This new level terrain design will finally allow a more game like and such more enjoyable experience for the user. We may implement different boundary conditions (floor, ceiling etc.) that adapt as the player proceeds (i.e. if a certain height is reached, the floor becomes lethal, or the player cannot go above a certain threshold).

These changes will be designed in conjunction with #90 these multiple game levels will be dependent on certain level features being implemented. 

# Examples
The player could now run into a section where they are forced to climb a hilly section; upon doing so, the floor would have moved up as well, and when utilised following #101, change a new level for the floor for which the player will no longer be able to cross.

# Dependencies
- Some of  Feature #101 will need to be pre-decided to decide terrain
- Team 2 for Feature #90 will need to have been met in order to discuss level layout

# Milestone
Task #114 
Task #108 
- [x] Implement new floor system for level 1
- [x] Implement new floor system for level 2
- [x] Implement player actions in relation to floor changes
- [x] Design floor layout; this includes any pit falls, valleys and hills

# Members
- Liam Hall @Gir3245 
- Onai Chenje @K0zzas17 
- Yee Ping @yeegoh 
- Sarah Han @sh4453 

# Documentation
[Main Game Floor](https://github.com/UQdeco2800/2021-studio-3/wiki/Main-game-floor-implementation-changes)

**Comment by default-jamc** [comment]
Hi guys, this sprint we're implementing some additional player movements (#93). We were wondering if you guys intend on implementing any sort of pitfalls or walls in the new terrain, as we're interested in implementing a wall jump. Thanks!

**Comment by K0zzas17** [comment]
Will need to discuss with Team-2 concerning possible Milestones needing implementing on #90 on the programming side

**Comment by default-jamc** [comment]
Hey @K0zzas17, sorry for taking so long to respond. That's all good, for now I've moved the wall-jump implementation to an extra (#93) while the level terrain is being developed :).
