### ISSUE TITLE
Introduce game story & context to player

### ISSUE THREAD

**Issue by default-jamc** [UQdeco2800/2021-studio-3#89]
# Description
First impressions are important. To provide brief background and context to the game, the player will be informed through a sequence of story-telling images. These images will contain little, but descriptive text which will introduce the game conflict/problem and the end goal. 

**A potential brief game description:**
[Planet name] is being shaken and stirred by catastrophic meteor events and overrun by all kinds of evil forces. You must navigate the rugged terrain and return to your spaceship to escape the planet before it's too late.

## Milestones
- [x] Write game description (18/09)
- [x] Create storyboard (18/09)
- [x] Design game introduction graphics (20/09)
- [x] Perform user testing in conjunction with #95 task (24/09)
- [x] Update wiki

## Documentation
[Introduction Screens User Testing](https://github.com/UQdeco2800/2021-studio-3/wiki/Introduction-Screens-User-Testing)
