### ISSUE TITLE
Progress / Checkpoint tracker

### ISSUE THREAD

**Issue by K0zzas17** [UQdeco2800/2021-studio-3#9]
### **Description** 
Rewarding players for reaching certain levels / achievements is paramount in ensuring the player doesn't get discouraged, as well as ensuring they feel accomplished for clearing a level or section. One such reward for this achievement is the checkpoint feature. This feature will determine a range of checkpoints where upon reaching them, will allow the player to respawn at their location if they die afterwards. Any items they've collected will also remain permanently after the checkpoint. These predetermined checkpoints will be visible to the player under a progress option, and upon passing them the player will be notified in the win / loss visualization described in ticket #8 The possibility for items to be recovered upon passing the obstacle that stopped the player on the run prior could be implemented in the future.

### **Dependencies** 
- The win / loss condition (Ticket #8) will needed to be implemented, in order for a link to be made to the player's current progress
- A main menu with a "Continue / load" feature from which a player can load a run from a checkpoint
- A menu where the player can monitor their progress and items

	
### **Sub-Features**
- The loss condition described in feature #8 will feature a continue option which will take the player to the previous checkpoint. A start-over option could also be explored. 
- Progress monitoring via a numbered level / checkpoint system will be designed

### **Examples**
Player will pass by a visual signal that shows they have completed a portion of the level/game
A progress bar will be on screen during the gameplay show how much longer a player has until the end of the level/game
Players will have a menu they can access anytime showing their items 

### **Milestone**
- [x] Establish how many checkpoints will be in the game and at which intervals - Aug 23

- [x] Design checkpoint icons - Aug 25

- [x] Design the menu - Aug 25

- [x] Documentation of checkpoint icons and menu on wiki - Aug 26

- [x] Implement checkpoint logic -  Aug 26

- [x]  Implement a progress bar on screen - 

- [x] Implement  checkpoint logic for an obstacle and integrate into pop up menus - Aug 31

### Members
Onai Chenje (K0zzas17)
Liam Hall (Gir3245)
Sarah Han (sh4453)
Abin Philip
