### ISSUE TITLE
Multiple game-level functionality

### ISSUE THREAD

**Issue by ShiyanSu** [UQdeco2800/2021-studio-3#90]
# Description

To make the game more engaging and challenging, our team is going to implement multiple game-level functionality for this game. Within this functionality, there are several main functional parts that we are going to achieve:

1. There are different game areas for various levels, especially three for this feature, and the player could be able to swich between each level when they successfully finish the current level.
2. The background of each game level should be designed and implemented corresponding to the storyline of each level.
3. Ajust the position of the enemies for each level.

## Examples

- Same as the super mario, when the player successfully reaches the end of the current level, they will be able to jump into the next level which has different backgound, difficulty and arrangement of obstacles.

# Dependencies

# Milestones

- [x] Design background for each level. (Sept. 25) #130 
- [x] Conduct user testing for both storyline and background appearance of each level. (Sept. 26)
- [x] Write the functions that deal with the change of levels. (Sept. 26) #132 
- [x] Write the game areas for new levels. (Sept. 26) #126 
- [x] Write the game screens for new levels. (Sept. 26) #131 
- [x] Fix the bug of the UI components. (Sept. 27) #133 
- [x] Implement the background for new levels. (Sept. 27) #134 
- [x] Adjust the position of enemies for three levels. (Sept. 28)
- [x] Write JUnit test. (Sept. 30) #148 
- [x] Write and update the wiki document. (Sept. 30) 

*Completion Deadline:* Sept. 30

# Documentation 
- [game background documentation](https://github.com/UQdeco2800/2021-studio-3/wiki/Game-Background)
- [wiki for multiple game-level](https://github.com/UQdeco2800/2021-studio-3/wiki/Multiple-game-level)
# Members 

- Emily Zeng (@emily-dl) (Emily Zeng)
- Shiyan Su (@ShiyanSu) (Shiyan Su)
- Zhiyuan Xu (@DLAmeng)
- Thomas Mann (@44806158)

**Comment by Gir3245** [comment]
Hey guys I have updated the way levels will load the floor for [#108,](https://github.com/UQdeco2800/2021-studio-3/issues/108) It will now read it from a map file under assets/floor-levels
and it is in the form of d,x,y where d is the distance factor, and x and y are the coordinates. Please have a look at  terrain_floor_branch to see how its been incorporated. The logic for this can be found on ForestGameArea in the function spawnTerrain(). can you just keep this in mind as you incorporate your levels.

**Comment by ShiyanSu** [comment]
> Hey guys! So team 3 is looking at polishing some of the game features and after speaking with Jack we thought it would make more sense if the player was able to move through the fire and take damage rather than forcing them to navigate around it. Would you be okay with us making this change? (#27 is the ticket reference)

Yes, we have already figured out that change, it's good and makes the fire more sensible.
