### ISSUE TITLE
Refine character movement animations

### ISSUE THREAD

**Issue by paulchoi610** [UQdeco2800/2021-studio-3#91]
# Description
Animations for character movements (Idle, Sprinting, Walking and Jumping) need to be refined. Visually, there are size and other inconstencies between each animation state that should be resolved. There are also numerous problems regarding the changing of animations depending on the player state (e.g. the jump animation continues to loop upon activation regardless of if the jump has completed). The character model must also revert back to previous damage states when health is regenerated through items.

Improving these aspects of the character movement will create a more seamless and responsive player experience, increasing user experience and enjoyment.

# Milestones
**Goal 1 - Create new animation frames for inconsistent player states** (Ticket #X) (@X)
- [ ] Alter the size of the front idle view of the character 
- [ ] Alter the damage aesthetic of the front idle view to match that of the side view
- [ ] Convert into GDX spritesheet and atlas

# Documentation
...
Members
Sebastian (@BasJW)
Paul (@paulchoi610)
Mihir (@ShahM1h1r )
Justin (@SirAardvark ) (Justin Aavik)
Kevin(@Dollar0712 ) (Kaipeng Zhang)

**Comment by paulchoi610** [comment]
To everyone, feel free to add more goals specific to the tasks that you will complete.

**Comment by default-jamc** [comment]
Hi guys! I've just finished implementing double jump (#94) and changing the way the jump mechanism works (#118). I just wanted to give you guys a heads up that I plan to make changes to your [Player Jumping Functionality wiki page](https://github.com/UQdeco2800/2021-studio-3/wiki/Player-Jumping-Functionality) to discuss the changes (adding the new information only; I won't remove your current implementation explanation :D).  Cheers.

**Comment by SirAardvark** [comment]
Thanks for letting us know. When you push the changes to your branch I will have a look at how you implemented it as we spoke about a few ways in the studio.

**Comment by default-jamc** [comment]
Awesome. There was definitely a lot of prototype implementations before this final one haha :'). I'll let you know when the changes have been pushed.

**Comment by default-jamc** [comment]
Hey @SirAardvark, I've just pushed the double jump and jumping overhaul code. You can have a look at the pull request here #122. Feel free to review and merge the request if you like :D

**Comment by SirAardvark** [comment]
I will have a look at the code and the pull request after I get home from work around 1.00pm ish.
