### ISSUE TITLE
Sound Effects Design

### ISSUE THREAD

**Issue by default-jamc** [UQdeco2800/2021-studio-3#92]
## **Description**
Design of movement, enemy and atmospheric sounds provides a more immersive experience for the player, giving character to the world around them. Sound effects relating to UI elements, environmental interactions and checkpoints (eg, winning or losing) will be added into the game. The implementation will involve researching similar genre games to see how their sound design helps to express the environment, before creating our own effects. User testing will determine the suitability of the effects before their final implementation into the game. We endeavour to implement the following sound effects:

|*Game Sounds*|*Interactive Sounds*|*Combat Sounds*|
|-|-|-|
|Winning a level|Picking up buffs & debuffs|Robot inflicting damage on the player (swinging arm)|
|Losing a level||UFO inflicting damage on the player (beam)|
|Pausing the game|||
|Clicking menu buttons|||

### **Sub-feature / Components**
- Research into similar genres of video game & sound production
- Design initial sounds 
- User testing to determine suitability of sounds
- Implementation into final product

### **Examples**
- **Game Sounds:** When the player interacts with the UI, certain sounds will occur.
- **Interactive Sounds:** When the player interacts with the world around them, certain sounds will occur
- **Combat Sounds:** When the player engages in combat, certain sounds will occur.

## **Milestones**
- [x] Create initial wiki page (Sept. 17)
- [x] Research into other games & their sound design (Sept. 20)
- [x] Design *Game Sounds* (Sept. 23) (#117) @Su-LAN 
    - [x] Winning a level
    - [x] Losing a level
    - ~Pausing the level~
    - [x] Pressing menu buttons (#103) @WendyW16 
        - ~Complete user testing~
        - ~Update relevant wiki pages~ 
- [x] Design *Interactive Sounds* (Sept. 27)
    - [x] Picking up buffs & debuffs
        - [x] Complete user testing
        - [x] Update relevant wiki pages 
- [x] Add music to the game (Sept. 29) (#117) @Su-LAN 
   - [x] Main Menu Music
   - [x] Level One Music
- [x] Implement sounds into the final game (Oct. 3)
- [x] Add new changes to game Wiki (Oct. 5)

*Completion Deadline:* Oct. 5

## **Extras**
- Design *Combat Sounds*: Combat sounds will include;
   - Robot attacking
   - UFO beam 
 

## **Documentation**
- [Sound Effects wiki page](https://github.com/UQdeco2800/2021-studio-3/wiki/Sound-Effects)

## **Members**
- Jazmin (@default-jamc)
- Niko (@n1ko4fun)
- Ranee (@raneechu)
- Su (@Su-LAN)
- Wendy (@WendyW16)

**Comment by default-jamc** [comment]
[23/09] _Changelog_: Combat sounds was moved to an **Extra** and Main Menu & Level Music was moved to a **Milestone**. This swap was made as there is the potential for more enemies to be added into the game yet, and we felt it was more appropriate to create sound effects for an already-completed feature first.

**Comment by default-jamc** [comment]
[02/10] _Changelog_: 
- The layout of the **Extras** listing was changed so that the extras don't contribute to the total amount of tasks in the Feature.
- The #103 task was linked to the '_Pressing Menu Buttons_' sub-task

**Comment by Su-LAN** [comment]
![Loading Screen UML](https://user-images.githubusercontent.com/88018784/135891191-d98c7408-2d2d-40c2-868d-2804679e5741.png)

**Comment by Su-LAN** [comment]
![6dd6a1fea714769ebc57ff83e5c6a9d](https://user-images.githubusercontent.com/88018784/135892293-197ea297-0d70-4ac7-9fdb-b100a82c3816.png)

**Comment by WendyW16** [comment]
<img width="1440" alt="屏幕快照 2021-10-05 下午12 15 52" src="https://user-images.githubusercontent.com/88033083/135949806-56e50d6b-4cd7-4cd3-9fd6-b31348aea897.png">
