### ISSUE TITLE
Additional Player Movement

### ISSUE THREAD

**Issue by default-jamc** [UQdeco2800/2021-studio-3#93]
## **Description**
Being a platformer, the player would benefit from having additional ways to navigate their environment. Additional movements will be added to the game to allow the player to navigate the obstacles, enemies and terrain in a more interesting way. The implementation will involve designing movements which will be available to the player by default.  Some examples of movements which may be implemented are listed below

| movement | effect |
|------|-------|
| double jump | while mid-air, the player can jump again |
| wall jump | while touching a wall, the player can use it to jump in the other direction|
| instant drop| while mid-air, the player can drop to the ground faster |
|roll| the player can roll to move forwards faster|

### **Sub-feature / Components**
- Implementation of the movements
- Design of the new atlases defining the movement
- User testing to determine suitability of controls

## **Dependencies**
- The functionality of wall-jump requires that the game map have some sort of wall or obstacles to bounce off that will benefit the player. The implementation of wall-jump will depend on the outcome of (#80)

## **Milestones**
- [x] Overhaul of jumping system to remove dependencies on Timers (Sept. 23) #118 (@default-jamc)
- [x] Implement *double jump* (Sept. 24) #94 (@default-jamc)
    - [x] Write code logic
    - [x] Document code 
    - [x] Complete user & JUnit testing
    - [x] Update relevant wiki pages
- [x] Implement *roll* (Sept. 28) #125 (@default-jamc)
    - [x] Write code logic
    - [x] Document code 
    - [x] Complete user & JUnit testing
    - [x] Update relevant wiki pages
- [x] Design atlases for additional player movements (Sept. 30) (#107) (@n1ko4fun)
    - [x] Roll
    - [x] Instant drop
    - [x] (Extra) Wall jump
- [x] UML and Sequence Diagram (Sept 25) (@raneechu) 
- [x] Add new changes to game Wiki (Oct. 5)

*Completion Deadline:* Oct. 5

## **Extras**
- Implement *wall jump*
    - Write code logic
    - Document code 
    - Complete user & JUnit testing
    - Update relevant wiki pages
- Implement *instant drop* 
    - Write code logic
    - Document code 
    - Complete user & JUnit testing
    - Update relevant wiki pages

## **Documentation**
- [Jumping Wiki Page](https://github.com/UQdeco2800/2021-studio-3/wiki/Player-Jumping-Functionality)
- [Double Jumping Wiki Page](https://github.com/UQdeco2800/2021-studio-3/wiki/Player-Double-Jumping-Functionality)

## **Members**
- Jazmin (@default-jamc)
- Niko (@n1ko4fun)
- Ranee (@raneechu)
- Su (@Su-LAN)
- Wendy (@WendyW16)

**Comment by default-jamc** [comment]
[23/09] _Changelog_: the implementation of wall-jump has been moved to an **Extra** due to it's dependency on the outcome of #80

**Comment by default-jamc** [comment]
[25/09] _Changelog_: Added the new [Double Jumping Functionality Wiki Page](https://github.com/UQdeco2800/2021-studio-3/wiki/Player-Double-Jumping-Functionality) link.

**Comment by default-jamc** [comment]
[29/07] _Changelog:_ 
- Extended the '_UML and Sequence Diagrams_' task. 
- Added #107 to the '_Design atlases for additional player movements_' task.

**Comment by raneechu** [comment]
[02/10] _Changelog:_ the implementation of instant drop has been moved to an Extra due to prioritising the loading screen as a more essential feature of the game.

**Comment by default-jamc** [comment]
[04/10] _Changelog_: The tasks in the **Extras** section had their format changed so that they do not contribute to the overall amount of tasks for this Feature.
