### ISSUE TITLE
Implement Double Jump Functionality

### ISSUE THREAD

**Issue by default-jamc** [UQdeco2800/2021-studio-3#94]
# Description
**Task Name:** Implement Double Jump Functionality.
**Feature:** Additional Player Movement #93  

Double jump will allow the player to jump once more while mid-air. The player will not be able to jump again until they have hit the ground.

Implementation of double jump will make changes to the `KeyboardPlayerInputComponent` class. Another class may be created to handle the additional movement also.

# Milestones
- [ ] Create Double Jump Wiki Page (Sept. 18)
- [ ] Implement Double Jump (Sept. 19)
- [ ] Document code (Sept. 19)
- [ ] Complete JUnit testing (Sept. 20)
- [ ] Update Wiki documentation (Sept. 20)

**Completion Deadline:** Sept. 20

# Documentation
- [*To be created*](https://github.com/UQdeco2800/2021-studio-3/wiki)

# Member
- Jazmin (@default-jamc)

**Comment by default-jamc** [comment]
[25/09] _Changelog_: Added the new [Double Jump Functionality Wiki Page](https://github.com/UQdeco2800/2021-studio-3/wiki/Player-Double-Jumping-Functionality) link.
