### ISSUE TITLE
Redesign Main Screen

### ISSUE THREAD

**Issue by sh4453** [UQdeco2800/2021-studio-3#95]
# Description 
Task: Redesign Main Screen 
Feature: #75 

Design a new main screen based on the game's theme and visuals. Initial designs will be sketched out on paper then fleshed out on Illustrator. 

# Milestones
- [x] Sketch potential ideas - 17/9 
- [x] Create main screen 1 draft on illustrator - 18/9
- [x] Create main screen 2 draft on illustrator - 19/9
- [x] Finalise designs - 21/9 
- [x] Update Wiki documentation - 22/9

# Documentation
[Main Start Screen Wiki Page](https://github.com/UQdeco2800/2021-studio-3/wiki/Main-Start-Screen)
# Members
Sarah Han (@sh4453)
