### ISSUE TITLE
Implement instant drop functionality

### ISSUE THREAD

**Issue by raneechu** [UQdeco2800/2021-studio-3#97]
# Description
**Task Name**: Implement instant drop functionality
**Feature**: Additional Player Movement #93 

Instant drop allows the player to fall immediately to the ground at a faster speed compared to if it were to fall naturally. This allows them to dodge obstacles that are moving around in the air i.e. robot and ufo obstacles.

Implementing this functionality plans to make changes to the `KeyboardPlayerInputComponent` class and possibly `PlayerStateComponent` if animations are implemented this sprint.

# Milestones
- [ ] Create Instant Drop Wiki Page (Sept 20)
- [ ] Implement Instant Drop (Sept 22)
- [ ] Document Code (Sept 22)
- [ ] Junit testing (Sept 23)
- [ ] Update Wiki Documentation (Sept 23)

# Documentation
- [Wiki Page](https://github.com/UQdeco2800/2021-studio-3/wiki/Player-Instant-Drop)

# Member
- Ranee @raneechu
