### ISSUE TITLE
Implement left player movement animations

### ISSUE THREAD

**Issue by SirAardvark** [UQdeco2800/2021-studio-3#98]
## Description 
**Feature:** Refine character movement animations #91 

The player currently only have movement animations for moving right. This is visually confusing when the player is moving left but looking right. 

To save on file size we will us the right movement animations and flip them. This will also keep left and right movement the same. 

## Milestones
- [x] Flip the animations
- [x] Add the left player movement animations into the atlas file
- [x] Implement into PlayerStateComponent by adding new atlas names, direction state and manage direction state
- [x] Implement into KeyboardPlayerInputComponent
- [x] Implement into current JUnit tests
- [x] Update the Player-State-Manager Wiki

## Documentation
**Wiki Page:** https://github.com/UQdeco2800/2021-studio-3/wiki/Player-State-Manager

## Member
Justin (@SirAardvark )

**Comment by SirAardvark** [comment]
18/09 - Flipped the animations and added them into the Atlas files, PlayerStateComponent and partially into KeyboardInputComponent

**Comment by SirAardvark** [comment]
20/09 - Fully integrated into `KeyboardPlayerInputComponent`  (0ef01c4afbcf4680147c1405938a51972fa5a688), Updated JUnits tests (a9660c2808b76894e5a40a69f606bfbea36b10df), Updated the Player-State-Manager Wiki.
