### ISSUE TITLE
Integrate animation to change when health buff is picked up

### ISSUE THREAD

**Issue by SirAardvark** [UQdeco2800/2021-studio-3#99]
## Description
Feature: Refine character movement animations #91

Team-3 implemented buff/debuffs which can add health or remove health from the player. Currently there is nothing that checks if the players health has changed if the player is not moving. 

The PlayerAnimationController also does not have a way to set the animations back to full health.

## Milestones
- [x] Add a listener/trigger in the Set Health function
- [x] Update the PlayerAnimationController to include go back to full health animations
- [x] Test by losing health and picking up a healing buff

## Member
Justin (@SirAardvark )

**Comment by SirAardvark** [comment]
20/09 - Fully Integrated out animations to work anytime the players health is changed (00e13cdd2feb5ed0736e5a11b11f0dcbd736ed04). `PlayerAnimationContoller` now can update to full health.
